### ISSUE TITLE
Struktur in Code/Dokumentation bringen

### ISSUE THREAD

**Issue by JulianeOrt** [imbitdhbwma/brillianplatform#11]
Code in GitHub anschauen, verstehen welche Codeteile zusammenhängen und wie diese reorganisiert werden, sodass Problemstellen im Code schnell gefunden werden können.

Deadline: Sprint 1 Ende (estimated Donnerstag, 30.10.19)

**Comment by LauraBrinks** [comment]
Wird bei neuen Tickets nebenbei erledigt
