### ISSUE TITLE
Jenkins implementieren

### ISSUE THREAD

**Issue by ErikGarstka** [imbitdhbwma/brillianplatform#14]

**Comment by imbitdhbwma** [comment]
jenkins UI [hier](http://3.120.219.127:8080/jenkins/) erreichbar

**Comment by najann** [comment]
Ich werde vorerst nur neue Jenkins Workflows für unser Repo auf dem Q Server erstellen

**Comment by najann** [comment]
Das Speicherproblem sollte gelöst sein. Die Workflows für Q funktionieren jetzt.

**Comment by najann** [comment]
Außerdem, bekommen eingetragenen Mailadressen nach jedem Jenkins build eine email
