### ISSUE TITLE
CUR: Veralteter Link "Wie dual bin ich?"

### ISSUE THREAD

**Issue by LauraBrinks** [imbitdhbwma/brillianplatform#15]
Wenn das "Wie dual bin ich?" Quiz mit "grüner Ampel" beendet wird, erscheint der folgende Link der nicht funktioniert.

![Anmerkung 2019-10-25 120806](https://user-images.githubusercontent.com/56722107/67563186-7f674800-f720-11e9-80a0-260aba912499.png)
![Anmerkung 2019-10-25 120904](https://user-images.githubusercontent.com/56722107/67563187-7f674800-f720-11e9-981e-deb88ff997cc.png)

**Comment by redisa** [comment]
Hallo Laura,
kannst du uns dann bitte einen Link auf der neuen Seite raussuchen auf der etwas interessantes stehen könnte oder möchtest du dass die Verlinkung einfach gelöscht wird?

**Comment by DigitaleMedienDHBW** [comment]
Vorschlag: Verweisen sie doch auf
www.mannheim.dhbw.de/dual-studieren/duales-studium/vorteile-eines-dualen-studiums

Mit freundlichen Grüßen 
Prof. Peter Mayr

**Comment by redisa** [comment]
Es wurden alle Links die von dem Wie dual bin ich Quiz ausgehen an die neue DHBW Webseite angepasst.

**Comment by redisa** [comment]
Bitte testen! Es wurden die Links für verschieden Mögliche Ausgangsmöglichkeiten des Quizzes korrigiert, daher bitte alle ca.10 Versionen und die Links auf die dabei verwiesen wird testen.

Hier die verschiedenen Antworten:
switch (AnswerIndex) {
				case 111:
					ResultText = "Das duale Studium scheint deinen Interessen und Wünschen nicht zu entsprechen.<br>Du solltest dich nach Alternativen umschauen!";
					color = red;
					break;
				case 112:
					ResultText = "Das duale Studium scheint deinen Interessen und Wünschen nicht zu entsprechen.<br>Du solltest dich nach Alternativen umschauen!";
					color = red;
					break;
				case 113:
					ResultText = "Du scheinst noch unentschlossen zu sein.<br>" + "<a href=https://www.mannheim.dhbw.de/dual-studieren/bachelor-studienangebot target=_blank>Hier </a>" + "findest du viele interessante, duale Studienangebote der DHBW Mannheim!";
					color = amber;
					break;
				case 114:
					ResultText = "Dein Studium ist dir zu theoretisch?<br>" + "<a href=https://www.mannheim.dhbw.de/dual-studieren/bachelor/wirtschaft/wirtschaftsinformatik/imbit/studienuebersicht target=_blank>Hier </a>" + "findest du Informationen zu den Praxiseinsätzen während des dualen Studiums!";
					color = green;
					break;
				case 121:
					ResultText = "Das duale Studium scheint deinen Interessen und Wünschen nicht zu entsprechen.<br>Du solltest dich nach Alternativen umschauen!";
					color = red;
					break;
				case 122:
					ResultText = "Du bist noch unentschlossen?<br>" + "<a href=https://www.dhbw-mannheim.de/ target=_blank>Hier </a>" + "bekommst du Antworten auf deine Fragen!";
					color = amber;
					break;
				case 123:
					ResultText = "Die Idee des dualen Studiums scheint dir zu gefallen.<br>" + "<a href=https://www.mannheim.dhbw.de/dual-studieren/duales-studium/vorteile-eines-dualen-studiums target=_blank>Hier </a>" + "kannst du dich über die Vorteile eines dualen Studiums informieren!";
					color = green;
					break;
				case 124:
					ResultText = "Die Idee des dualen Studiums scheint dir zu gefallen.<br>" + "<a href=https://www.mannheim.dhbw.de/dual-studieren/duales-studium/vorteile-eines-dualen-studiums target=_blank>Hier </a>" + "kannst du dich über die Vorteile eines dualen Studiums informieren!";
					color = green;
					break;
				case 131:
					ResultText = "Die Idee des dualen Studiums scheint dir zu gefallen.<br>" + "<a href=https://www.mannheim.dhbw.de/dual-studieren/duales-studium/vorteile-eines-dualen-studiums target=_blank>Hier </a>" + "kannst du dich über die Vorteile eines dualen Studiums informieren!";
					color = amber;
					break;
				case 132:
					ResultText = "Die finanziellen Möglichkeiten, die dir das duale Studium bietet, scheinen dir zu gefallen.<br>" + "<a href=https://www.mannheim.dhbw.de/dual-studieren/duales-studium/vorteile-eines-dualen-studiums target=_blank>Hier </a>" + "kannst du dich über die Vorteile eines dualen Studiums informieren!";
					color = green;
					break;
				case 133:
					ResultText = "Du und das duale Studium, das passt!<br>Welche Studiengänge dich an der DHBW Mannheim erwarten, siehst du " + "<a href=https://www.mannheim.dhbw.de/dual-studieren/bachelor-studienangebot target=_blank>hier</a>" + "!";
					color = green;
					break;
				case 134:
					ResultText = "Du und das duale Studium, das passt!<br>Welche Studiengänge dich an der DHBW Mannheim erwarten, siehst du " + "<a href=https://www.mannheim.dhbw.de/dual-studieren/bachelor-studienangebot target=_blank>hier</a>" + "!";
					color = green;
					break;
				case 211:
					ResultText = "Das duale Studium scheint deinen Interessen und Wünschen nicht zu entsprechen.<br>Du solltest dich nach Alternativen umschauen!";
					color = red;
					break;
				case 212:
					ResultText = "Duales Studium? Das passt!<br>Die finanziellen Möglichkeiten, die ein duales Studium bietet, nutzen viele Studierende um neue Orte, sowohl beruflich als auch privat, kennenzulernen:<br>" + "<a href=https://www.mannheim.dhbw.de/service/international-office target=_blank>Gute Gründe für ein Duales Studium</a>";
					color = green;
					break;
				case 213:
					ResultText = "Duales Studium? Das passt!<br>Die finanziellen Möglichkeiten, die ein duales Studium bietet, nutzen viele Studierende um neue Orte, sowohl beruflich als auch privat, kennenzulernen:<br>" + "<a href=https://www.mannheim.dhbw.de/service/international-office target=_blank>Gute Gründe für ein Duales Studium</a>";
					color = green;
					break;
				case 214:
					ResultText = "Duales Studium? Das passt!<br>Die finanziellen Möglichkeiten, die ein duales Studium bietet, nutzen viele Studierende um neue Orte, sowohl beruflich als auch privat, kennenzulernen:<br>" + "<a href=https://www.mannheim.dhbw.de/service/international-office target=_blank>Gute Gründe für ein Duales Studium</a>";
					color = green;
					break;
				case 221:
					ResultText = "Du bist noch unentschlossen?<br>" + "<a href=https://www.dhbw-mannheim.de/ target=_blank> Hier </a>" + "findest du Antworten auf deine Fragen!";
					color = amber;
					break;
				case 222:
					ResultText = "Duales Studium? Das passt!<br>Spannende Studiengänge der DHBW Mannheim findest du " + "<a href=https://www.mannheim.dhbw.de/dual-studieren/bachelor-studienangebot target=_blank>hier</a>" + "!";
					color = green;
					break;
				case 223:
					ResultText = "Super!<br>Du scheinst wie gemacht zu sein für ein duales Studium!<br>Deinen zukünftigen Arbeitgeber findest du bei deinem Studiengang: " + "<a href=https://www.mannheim.dhbw.de/dual-studieren/bachelor-studienangebot target=_blank>Zukunft planen</a>" + "!";
					color = green;
					break;
				case 224:
					ResultText = "Super!<br>Du scheinst wie gemacht zu sein für ein duales Studium!<br>Deinen zukünftigen Arbeitgeber findest du bei deinem Studiengang: " + "<a href=https://www.mannheim.dhbw.de/dual-studieren/bachelor-studienangebot target=_blank>Zukunft planen</a>" + "!";
					color = green;
					break;
				case 231:
					ResultText = "Die finanziellen Möglichkeiten, die dir das duale Studium bietet, scheinen dir zu gefallen.<br>" + "<a href=https://www.mannheim.dhbw.de/dual-studieren/duales-studium/vorteile-eines-dualen-studiums target=_blank>Hier </a>" + "kannst du dich über die weiteren Vorteile eines dualen Studiums informieren!";
					color = green;
					break;
				case 232:
					ResultText = "Klasse! Dir scheint ein duales Studium zu gefallen.<br>" + "<a href=https://www.mannheim.dhbw.de/dual-studieren/bachelor-studienangebot target=_blank>Hier </a>" + "findest du die verschiedenen dualen Studiengänge der DHBW Mannheim.";
					color = green;
					break;
				case 233:
					ResultText = "Super!<br>Du scheinst wie gemacht zu sein für ein duales Studium!<br>Melde dich doch an unserer " + "<a href=https://studyup.mannheim.dhbw.de/bewerberboerse/ target=_blank>Partnerbörse</a>" + " an und lass dich finden!";
					color = green;
					break;
				case 234:
					ResultText = "Super!<br>Du scheinst wie gemacht zu sein für ein duales Studium!<br>Melde dich doch an unserer " + "<a href=https://studyup.mannheim.dhbw.de/bewerberboerse/ target=_blank>Partnerbörse</a>" + " an und lass dich finden!";
					color = green;
					break;
				case 311:
					ResultText = "Du bist noch unentschlossen?" + "<a href=https://www.dhbw-mannheim.de/ target=_blank> Hier </a>" + "bekommst du Antworten auf deine Fragen.";
					color = amber;
					break;
				case 312:
					ResultText = "Die finanziellen Möglichkeiten, die dir das duale Studium bietet, scheinen dich nicht besonders zu interessieren.<br>Vielleicht begeistern dich " + "<a href=https://www.mannheim.dhbw.de/dual-studieren/duales-studium/vorteile-eines-dualen-studiums target=_blank>diese</a>" + "Vorteile mehr?";
					color = green;
					break;
				case 313:
					ResultText = "Sehr gut!<br>Du bringst viele wichtige Eigenschaften mit.<br>Finanziell scheinst du zwar abgesichert zu sein, aber das Gefühl selbstständig Geld zu verdienen, bekommst du nur " + "<a href=https://www.mannheim.dhbw.de/dual-studieren/bachelor-studienangebot target=_blank>hier!</a>";
					color = green;
					break;
				case 314:
					ResultText = "Sehr gut!<br>Du bringst viele wichtige Eigenschaften mit.<br>Finanziell scheinst du zwar abgesichert zu sein, aber das Gefühl selbstständig Geld zu verdienen, bekommst du nur " + "<a href=https://www.mannheim.dhbw.de/dual-studieren/bachelor-studienangebot target=_blank>hier!</a>";
					color = green;
					break;
				case 321:
					ResultText = "Klasse! Dir scheint ein duales Studium zu gefallen.<br>Melde dich gleich an unserer " + "<a href=https://studyup.mannheim.dhbw.de/bewerberboerse/ target=_blank>Partnerbörse</a>" + " an und lass dich finden!";
					color = green;
					break;
				case 322:
					ResultText = "Super! Du scheinst für das duale Studium sehr geeignet zu sein!<br>Melde dich gleich an unserer " + "<a href=https://studyup.mannheim.dhbw.de/bewerberboerse/ target=_blank>Partnerbörse</a>" + " an und lass dich finden!";
					color = green;
					break;
				case 323:
					ResultText = "Super! Du bringst viele wichtige Eigenschaften mit!<br>Melde dich gleich an unserer " + "<a href=https://studyup.mannheim.dhbw.de/bewerberboerse/ target=_blank>Partnerbörse</a>" + " an und lass dich finden!";
					color = green;
					break;
				case 324:
					ResultText = "Super! Du bringst viele wichtige Eigenschaften mit!<br>Melde dich gleich an unserer " + "<a href=https://studyup.mannheim.dhbw.de/bewerberboerse/ target=_blank>Partnerbörse</a>" + " an und lass dich finden!";
					color = green;
					break;
				case 331:
					ResultText = "Super! Du scheinst für das duale Studium sehr geeignet zu sein!<br>Melde dich gleich an unserer " + "<a href=https://studyup.mannheim.dhbw.de/bewerberboerse/ target=_blank>Partnerbörse</a>" + " an und lass dich finden!";
					color = green;
					break;
				case 332:
					ResultText = "Spitze! Du scheinst wie für das duale Studium gemacht zu sein! Melde dich doch an unserer "  + "<a href=https://studyup.mannheim.dhbw.de/bewerberboerse/ target=_blank>Partnerbörse</a>" + " an und lass dich finden!";
					color = green;
					break;
				case 333:
					ResultText = "Wahnsinn! Deine Vorstellungen passen genau zum dualen Studium.<br>Registriere dich an unserer "  + "<a href=https://studyup.mannheim.dhbw.de/bewerberboerse/ target=_blank>Partnerbörse</a>" + " und lass dich von deinem künftigen Ausbildungsunternehmen finden!";
					color = green;
					break;
				case 334:
					ResultText = "Wahnsinn! Deine Vorstellungen passen genau zum dualen Studium.<br>Registriere dich an unserer "  + "<a href=https://studyup.mannheim.dhbw.de/bewerberboerse/ target=_blank>Partnerbörse</a>" + " und lass dich von deinem künftigen Ausbildungsunternehmen finden!";
					color = green;
					break;

**Comment by NicolasSimon99** [comment]
@StevenHerrenknecht und @MarvinGi bitte zusammen testen!
(teilt euch auf)

**Comment by StevenHerrenknecht** [comment]
Case 134, 211, 222, 311, 333, 334 funktionieren wie gewünscht. Die restlichen Cases werden von @MarvinGi getestet.

**Comment by MarvinGi** [comment]
@NicolasSimon99 restliche Cases funktionieren

**Comment by NicolasSimon99** [comment]
@JulianeOrt

**Comment by JulianeOrt** [comment]
In Backlog vermerkt (04.11.19)
