### ISSUE TITLE
CUR: Hintergrund fehlt

### ISSUE THREAD

**Issue by Lara-u** [imbitdhbwma/brillianplatform#20]
Video (mit Bläschen) im Hintergrund fehlt, daher erscheint nur ein weißer Bildschirm auf dem die weiße Schrift nicht sichtbar ist.

**Comment by JulianeOrt** [comment]
Detaillierte Screenshots siehe Ordner 6 in Screenshots 
https://drive.google.com/drive/folders/1nNWFSUqAB7Uy6zbrcIlaTRE27kq-VbqB?usp=sharing

**Comment by DigitaleMedienDHBW** [comment]
Hallo Frau Ort,

ich sehe nur dreimal denselben Screenshot - s.u.  Gibt es noch nicht mehr?

Mit freundlichen Grüßen
Prof. Peter Mayr

**Comment by JulianeOrt** [comment]
Hallo Herr Mayr (@DigitaleMedienDHBW)
ich habe in dem Ordner https://drive.google.com/drive/folders/1nNWFSUqAB7Uy6zbrcIlaTRE27kq-VbqB?usp=sharing noch weitere Screenshots hinzugefügt, die bei Benutzung des Safari-Browsers auftreten, sobald man auf der Curriculum-Seite ist.
Der Fehler zieht sich im gesamten Bereich des Curriculums durch, daher nehme ich an, dass der Fehler aus einer Stelle im Code hervorgeht und die davon abhängenden Webseiten somit alle auf dem gleichen Fehler basieren.

@ErikGarstka bitte korrigiere mich, wenn das so nicht stimmt und ihr weitere Screenshots benötigt, um zu sehen, auf welchen "Unterseiten" im Curriculum der Hintergrund überall fehlt.
Danke!

**Comment by DigitaleMedienDHBW** [comment]
Hallo Frau Ort,

danke für die Informationen; das Designteam hat ja schon einiges dokumentiert. 

Mit einigen Kommilitonen aus dem Technikteam haben wir am Freitag mit Safari auf Macintosh "getestet". Es sieht so, als ob die Inhalte der Curriculum-Seiten schon geladen werden, aber dass das dunkelblaue Hintergrundvideo nicht richtig platziert ist und nicht dargestellt wird (z-Index?); daher erscheint der weiße Text auf weißem Grund (statt auf dem Video) und ist nicht erkennbar. Kann es sein, dass für Desktop-Safari eine Browser-Weiche eingebaut ist - das wäre unsinnig und ist bestenfalls für Mobile Safari eine Option.

Mit freundlichen Grüßen 
Prof. Peter Mayr

**Comment by ErikGarstka** [comment]
Das Background Video war auskommentiert. Bitte testen, ob das Problem damit bei Safari behoben wurde @NicolasSimon99

**Comment by NicolasSimon99** [comment]
@MarcinTrojanski bitte testen.

**Comment by MarcinTrojanski** [comment]
In Safari funktioniert nun auch das Hintergrundvideo im CUR! Er tritt nicht mehr auf, egal wie groß das Fenster ist oder wie man die Seite öffnet (Pfeiltasten, über klicken auf die Punkte und über die Menüleiste). 
Jedoch ist mir aber einmal ein Fehler aufgefallen, dieser ist aber nicht wieder erschienen, siehe dazu: #49 CUR: Sichtbarer Bereich anpassen.
