### ISSUE TITLE
CUR: Fehlende Links herausfinden

### ISSUE THREAD

**Issue by JulianeOrt** [imbitdhbwma/brillianplatform#21]
Laura sucht nach fehlenden Links heraus, an PO schicken

**Comment by LauraBrinks** [comment]
Unter Curriculum, IT, Datenbanken wird auf das Datenbanken Quiz verlinkt, der Link ist jedoch falsch. Richtiger Link: http://www.brillianideas.com:8080/brillianQUIZ/quiz/quiz.jsp?subject=datenbanken
![Anmerkung 2019-10-25 121943](https://user-images.githubusercontent.com/56722107/67622168-d7cd4100-f817-11e9-835c-420719b72991.png)
![Anmerkung 2019-10-25 122035](https://user-images.githubusercontent.com/56722107/67622169-d7cd4100-f817-11e9-9ebe-130f7039bb9a.png)

**Comment by LauraBrinks** [comment]
Unter Curriculum, WI, Fallstudie ist der Link zum Projekt mit dem Heimatbund und der Stadt Ladenburg defekt. Die Verlinkte Seite existiert auf der neuen IMBIT Webseite nicht mehr. @DigitaleMedienDHBW gibt es eine alternative Adresse auf die man verlinken könnte?
![Anmerkung 2019-10-26 174320](https://user-images.githubusercontent.com/56722107/67622247-c7699600-f818-11e9-8545-47e8778ffe15.png)
![Anmerkung 2019-10-26 174549](https://user-images.githubusercontent.com/56722107/67622248-c7699600-f818-11e9-8fe0-5a354cce895b.png)

**Comment by LauraBrinks** [comment]
Unter Curriculum, WI, WI wird auf eine Probeklausur der Fernuni Hagen verlinkt die nicht mehr existiert. Eine alternative Probeklausur ist unter https://www.fernuni-hagen.de/wirtschaftswissenschaft/studium/download/pruefungen/31101_ss19.pdf zu erreichen.
![Anmerkung 2019-10-26 175818](https://user-images.githubusercontent.com/56722107/67622415-3d223180-f81a-11e9-9ba0-91dbbf2830f4.png)

**Comment by LauraBrinks** [comment]
Unter Curriculum, WI, Integrationsseminar wird keine Literaturliste angezeigt wenn oben rechts auf Integrationsseminar geklickt wird. Bei WI, Fallstudie tritt das gleiche Problem auf.
![Anmerkung 2019-10-26 175123](https://user-images.githubusercontent.com/56722107/67622442-765aa180-f81a-11e9-84da-d9e420958935.png)
![Anmerkung 2019-10-26 175227](https://user-images.githubusercontent.com/56722107/67622444-7c508280-f81a-11e9-9e7e-bd2b2e1cce8f.png)

**Comment by LauraBrinks** [comment]
Unter Curriculum, WI, Grundlagen Human Machine Interaction wird auf ein Video der SAP verlinkt das nicht mehr existiert. Ich konnte kein alternatives Video finden, deshalb würde ich Vorschlagen einfach auf die Webseite https://experience.sap.com/designservices/apphaus/heidelberg zu verlinken und den Text demenstprechen abzuändern (einfach das "Hier findest du ein Video dazu" löschen.
![Anmerkung 2019-10-26 180901](https://user-images.githubusercontent.com/56722107/67622579-ba9a7180-f81b-11e9-9817-fbb7bf3d3614.png)

**Comment by LauraBrinks** [comment]
Unter Curriculum, WI, Management funktionieren die Links zu den oberen beiden MOOCs nicht, da diese nicht mehr existieren. @jessilenwell könnt ihr da neue raussuchen und evtl. neue Texte dazu verfassen?
![Anmerkung 2019-10-26 183340](https://user-images.githubusercontent.com/56722107/67622968-f0415980-f81f-11e9-802d-9580c9bd3e6c.png)
![Uploading Anmerkung 2019-10-26 183423.png…]()

**Comment by LauraBrinks** [comment]
Unter Curriculum, Methodisch Grundlagen, Statistik sind zwei komplette Absätze als Link markiert. Bitte so abändern, dass der Link nur auf der Überschrift ist. Außerdem ist die rechte Spalte mit der Modulbeschreibung verschoben und ebenfalls als Link markiert (gehört zu der letzten Webseite links). 
![Anmerkung 2019-10-26 184400](https://user-images.githubusercontent.com/56722107/67623025-ae64e300-f820-11e9-8e34-7e3e128fbf16.png)
![Uploading Anmerkung 2019-10-26 184429.png…]()

**Comment by LauraBrinks** [comment]
Unter Curriculum Intercultural Management ist die Seite zu Business Anthropology nicht mehr erreichbar, ich vermute sie existiert nicht mehr.  Gleiches gilt für den Mondolingua online Kulturtest und den "Are you intercultural" Test.
 Da es relativ viele Einträge gibt auf der Seite würde ich vorschlagen einfach die Abschnitte zu löschen.

![Anmerkung 2019-10-26 185159](https://user-images.githubusercontent.com/56722107/67623119-0e0fbe00-f822-11e9-9bf1-4c71bfcafc32.png)
![Anmerkung 2019-10-26 185230](https://user-images.githubusercontent.com/56722107/67623120-11a34500-f822-11e9-8fdd-d0c6c90d4677.png)
![Anmerkung 2019-10-26 184837](https://user-images.githubusercontent.com/56722107/67623079-6d210300-f821-11e9-88a3-ae94e33d3d7d.png)

**Comment by LauraBrinks** [comment]
Unter Curriculum, IT, Grundlagen der IT ist der Link zum Binär / Dezimal / Hexa falsch, bitte ändern zu 
https://bin-dez-hex-umrechner.de/

![Anmerkung 2019-10-26 185655](https://user-images.githubusercontent.com/56722107/67623156-85dde880-f822-11e9-8a6e-bdc55f832f81.png)

**Comment by LauraBrinks** [comment]
Unter Curriculum, Methodische Grundlagen, Grundlagen wissenschaftliches Arbeiten wird auf die alte DHBW Webseite verlinkt. 

@DigitaleMedienDHBW wissen sie wo der Leitfaden auf der neuen Webseite zu finden ist? So weit ich weiß ist der er gar nicht mehr erreichbar. Könnten sie (auch aus persönlichem Interesse bezüglich Bachelorarbeit) vielleicht mal nachhaken ob der Leitfaden auf der neuen Webseite einbaut werden kann?
![Anmerkung 2019-10-26 185852](https://user-images.githubusercontent.com/56722107/67623217-11f01000-f823-11e9-8dbb-c15a966ff5da.png)

**Comment by LauraBrinks** [comment]
Unter Curriculum, WI, Neue Konzept wird auf ein Wiki verwiesen das ein IMBIT Kurs mal erstellt hat, der Link endet aber in einem 404 Error
![Anmerkung 2019-10-26 190320](https://user-images.githubusercontent.com/56722107/67623280-8dea5800-f823-11e9-8102-4757a0d58590.png)
@DigitaleMedienDHBW  wissen sie wie man da drauf zugreifen kann?

**Comment by LauraBrinks** [comment]
Unter Curriculum, ICM, Spanisch wird auf eine flache Webseite verlinkt unter Vitallingua, bitte ändern in https://www.vitalingua.de/spanisch-lernen-kostenlos.html
![Anmerkung 2019-10-26 190735](https://user-images.githubusercontent.com/56722107/67623311-eb7ea480-f823-11e9-8335-fc2b8c5332be.png)

**Comment by LauraBrinks** [comment]
Unter Curriculum, Praxisphasen ist die PDF für Praxisphasen im Ausland nicht erreichbar. Ich bin mir nicht sicher ob es wirklich das gleiche ist, aber das Dokument müsste jetzt unter https://www.mannheim.dhbw.de/fileadmin/user_upload/Studienangebot/Wirtschaft/Wirtschaftsinformatik/IMBIT/Praxisphasen-2018-IMBIT-FakW-DHBW-MA-201810.pdf erreichbar sein.
![Anmerkung 2019-10-26 191243](https://user-images.githubusercontent.com/56722107/67623369-a149f300-f824-11e9-9c62-002152d8dcfb.png)

**Comment by LauraBrinks** [comment]
@MarcinTrojanski bitte nochmal alles unter Curriculum nachschauen ob noch weitere Links nicht funktionieren.

**Comment by redisa** [comment]
Zu beiden Themen existiert keine Literaturliste. @jessilenwell könnt ihr dazu wenn es sinnvoll ist vielleicht noch Literatur heraussuchen?


> Unter Curriculum, WI, Integrationsseminar wird keine Literaturliste angezeigt wenn oben rechts auf Integrationsseminar geklickt wird. Bei WI, Fallstudie tritt das gleiche Problem auf. Ist das ein Fehler im Code oder existiert hier keine Literaturliste? Wenn nicht dann bitte ans PM-Team wenden!
> ![Anmerkung 2019-10-26 175123](https://user-images.githubusercontent.com/56722107/67622442-765aa180-f81a-11e9-84da-d9e420958935.png)
> ![Anmerkung 2019-10-26 175227](https://user-images.githubusercontent.com/56722107/67622444-7c508280-f81a-11e9-9e7e-bd2b2e1cce8f.png)

**Comment by redisa** [comment]
Alle Kommentare die mit einem 👍 Emoji makiert sind wurden umgesetzt.

**Comment by redisa** [comment]
Es wurden alle Links korrigiert. Für die Bereiche die verändert werden müssen oder neue Inhalte die von der alten Webseite integriert werden müssen wurden die Tasks #36 #37 #43 erstellt.

**Comment by redisa** [comment]
Bitte alle veränderten links (s.o.) testen, die nicht durch Task 36,37 und 43 eine inhaltliche Änderung erforedern. @NicolasSimon99

**Comment by NicolasSimon99** [comment]
@MarcinTrojanski kannst du das bitte abschließend testen.

**Comment by JulianeOrt** [comment]
@MarcinTrojanski sind alle Links getestet?

**Comment by MarcinTrojanski** [comment]
Curriculum, Wirtschaftsinformatik, Fallstudie: leitet auf die IMBIT Seite
Curriculum, Wirtschaftswissenschaften, Management: MOCS leiten auf die open2study Seite weiter, diese ist aber ohne Funktion
Curriculum, Wirtschaftsinformatik, Neue Konzepte, Wiki: bisher ist immer noch kein Wiki angebunden

**Comment by redisa** [comment]
Link Fallstudie wurde korrigiert. 
Für MOOCS wurde #36 geöffnet.
Das Wiki existiert nicht mehr.
@MarcinTrojanski bitte Fallstudie testen und schließen

**Comment by LauraBrinks** [comment]
@redisa Kannst du den Link zu dem Wiki dann noch löschen? Dann schließ ich das Ticket, hab alles nochmal getestet :)

**Comment by redisa** [comment]
@LauraBrinks ist erledigt aber noch nicht online. Kannst dieses Issue aber gerne schließen
