### ISSUE TITLE
Alt-Text erstellen

### ISSUE THREAD

**Issue by Lara-u** [imbitdhbwma/brillianplatform#22]
Alt-text bei Images hinzufügen.

**Comment by redisa** [comment]
Wurde erledigt. Viel Spaß beim Testen

**Comment by NicolasSimon99** [comment]
@redisa was genau wurde hier geändert und wie kann das getestet werden?

**Comment by redisa** [comment]
@NicolasSimon99 Es muss nichts getestet werden aber wir sollten alles an euch weitergeben. An sich wird jetzt wenn ein Bild nicht geladen werden kann eine kurze Beschreibung stattdessen angezeigt.

**Comment by NicolasSimon99** [comment]
@redisa also kann das Issue praktisch geschlossen werden?

**Comment by redisa** [comment]
@NicolasSimon99 Ja kann es 
@JulianeOrt

**Comment by JulianeOrt** [comment]
vermerkt im Backlog (7.11.)
