### ISSUE TITLE
Schrift bei QUZ

### ISSUE THREAD

**Issue by Lara-u** [imbitdhbwma/brillianplatform#23]
Quiz: größere Schrift bei Mobile-Version (rem, CSS Größenangabe),
Texte aus Browser-Version in Handy Version wieder einfügen

**Comment by pnt-linii** [comment]
Ich emfehle Schriftgröße **3.0 rem** für die Darstellung der Elementen "Untertitel" auf Mobile-Geräte.

**Comment by Lara-u** [comment]
Unter QuizOverview.css wurde für die Mobile-Version "display None Beschreibung" ausgeblendet, damit die Beschreibung unter der Überschrift des Quiz auch in der Mobile-Version angezeigt wird. Dazu mussten die definierten Parameter von .IntroText und . Untertitel hinzugefügt und in der Größe teilweise geändert werden.

**Comment by Lilu-S** [comment]
@JulianeOrt da #28 schon als gelöst markiert ist, schließe ich dieses Issue.
