### ISSUE TITLE
CRM / ICM: E.-Mail Problem

### ISSUE THREAD

**Issue by Lara-u** [imbitdhbwma/brillianplatform#24]
Bei Profiländerungen oder dem Anlegen von Benutzern, ... werden keine Notification E.-mails versendet

**Comment by Myprr** [comment]
Status: AWS wurde kompromittiert. Von dem Mailserver aus wurden spam mails verschickt, sodass Amazon den Mailserver geblockt hat. Amazon will das wir unsere Sicherheit anpassen, bevor der Mailserver freigeschaltet wird.

Anliegen von Mayr:
Eingehende Emails ablehnen/ nicht annehmen.
Ausgehende Emails dürfen nur von CRM/ICM verschickt werden.
Zusätzlich die Sicherheit anpassen.

Anliegen von Bendl:
CRM Registrirung (auch ohne Email) lauffähig machen. Ebenso ICM.

**Comment by Myprr** [comment]
Status Update: 
Eingehende Emails ablehnen/ nicht annehmen - ist möglich, kostet aber.
AWS bietet zusätzlichen Service welches nach vordefinierten Regeln bestimmte Aktionen vornimmt. In unserem Fall eingehende Emails ablehnen. Pro Interaktion werden 0,0000002 ct. berechnet. Sodass nach 1 mio. Abgelehnten mails nur 0,2 ct anfallen. Dennoch wir können nicht vorhersagen wieviele Interaktionen tatsächlich stattfinden werden. Muss am Freitag mit Prof. Mayr geklärt werden.

**Comment by Feederhigh5** [comment]
> Status Update:
> Eingehende Emails ablehnen/ nicht annehmen - ist möglich, kostet aber.
> AWS bietet zusätzlichen Service welches nach vordefinierten Regeln bestimmte Aktionen vornimmt. In unserem Fall eingehende Emails ablehnen. Pro Interaktion werden 0,0000002 ct. berechnet. Sodass nach 1 mio. Abgelehnten mails nur 0,2 ct anfallen. Dennoch wir können nicht vorhersagen wieviele Interaktionen tatsächlich stattfinden werden. Muss am Freitag mit Prof. Mayr geklärt werden.

E-Mail Empfang erfolgreich geblockt #75.

**Comment by Feederhigh5** [comment]
Übergangslösung #53 mit Googlemail funktioniert.
CRM und ICM sollte funktionieren, muss nun getestet werden.
Insbesondere die Zertifikate die man bei ICM anfordern kann müssen ausprobiert werden.

**Comment by Myprr** [comment]
Status: auf Ergebnis von #78 warten

**Comment by JulianeOrt** [comment]
ist das Issue somit auch gelöst? @Feederhigh5 @Myprr

**Comment by Myprr** [comment]
> 
> 
> ist das Issue somit auch gelöst? @Feederhigh5 @Myprr

Leider noch nicht. Wir haben schwierigkeiten mit den Anmeldedaten von AWS einzutragen.
Müssen auf das Ergebnis von #53 warten.
Die Mails werden momentan per gmail versendet.

**Comment by JulianeOrt** [comment]
@Myprr wird dieses Issue bis morgen gelöst? ansonsten bitte zu Sprint 4 verschieben.

**Comment by JosieRuehling** [comment]
Mails werden laut #53 noch per GMail versendet, deswegen wird das Issue in Sprint 4 verschoben. @Myprr @JulianeOrt

**Comment by Myprr** [comment]
Issue #53 erfolgreich geschloßen.

**Comment by Myprr** [comment]
Emails werden erfolgreich beim Registrieren versendet. Issue ist abgeschlossen.
