### ISSUE TITLE
STR: Wie dual bin ich wird überdeckt

### ISSUE THREAD

**Issue by JulianeOrt** [imbitdhbwma/brillianplatform#27]
Quiz wie dual bin ich wird von Bäschen-Video überdeckt (z-index)

**Comment by JulianeOrt** [comment]
Hier sind die Screenshots https://drive.google.com/open?id=175hT7sE1Pwzq0h4hH-V5TMU_iujgtUbt

**Comment by JulianeOrt** [comment]
@ErikGarstka wie ist der Status? Wenn mehr Zeit benötigt wird, bitte in Sprint 2 verschieben

**Comment by najann** [comment]
Das Problem dürfte gelöst sein.

**Comment by NicolasSimon99** [comment]
@MarcinTrojanski bitte in Safari testen.

**Comment by MarcinTrojanski** [comment]
Auf dem Testserver ist es nun auch bei Safari sichtbar und leitet auch zum Quiz weiter.

**Comment by NicolasSimon99** [comment]
@JulianeOrt
