### ISSUE TITLE
QUZ: Überschriften nicht responsiv

### ISSUE THREAD

**Issue by JulianeOrt** [imbitdhbwma/brillianplatform#28]
Screenshot siehe hier https://drive.google.com/drive/folders/14yLmNvCKCK0tr4QHGlbq33Vn2tghIyWs?usp=sharing

**Comment by Lara-u** [comment]
Wir werden die Schriftgröße auf ca. 3.0 rem für Mobile-Geräte anpassen und die Abstände, Umbrüche überprüfen.

**Comment by pnt-linii** [comment]
Der Inhalt der Texte muss angepasst werden, bzw. _&shy;_ muss im Text hinzugefügt werden, um die Umbrüche zu ermöglichen. Wir warten auf den Source Code _brillianQUIZ_ vom vorgängigen Kurs.

**Comment by DigitaleMedienDHBW** [comment]
Hallo zusammen,

weiche Trenner für Zeilenumbrüche fügen Sie bitte mittels &shy; (soft hyphen) ein.

Mit freundlichen Grüßen 
Prof. Peter Mayr 

> Am 28.10.2019 um 22:18 schrieb pnt-linii <notifications@github.com>:
> 
> Der Inhalt der Texte muss angepasst werden, bzw. ­ muss im Text hinzugefügt werden, um die Umbrüche zu ermöglichen. Wir warten auf den Source Code brillianQUIZ vom vorgängigen Kurs.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 



Mit freundlichen Grüßen, 
Prof. Peter Mayr, IMBIT 
Duale Hochschule Baden-Württemberg Mannheim 
Baden-Wuerttemberg Cooperative State University Mannheim 
Coblitzallee 1-9, D-68163 Mannheim 

Tel: +49 (0)621 4105 - 1158 
peter.mayr@dhbw-mannheim.de 
www.imbit.dhbw-mannheim.de

**Comment by pnt-linii** [comment]
Added soft hypen in Quiz Overview jsp für die Umbrüche.

**Comment by Lara-u** [comment]
Das sieht dann beispielsweise so aus: 
<p class="Untertitel">Wahr&shy;nehmungs&shy;psycho&shy;logie</p>

Dadurch passen sich die Umbrüche der Überschriften im Quiz auch an die Mobile-Version an.

**Comment by JulianeOrt** [comment]
@NicolasSimon99 bitte testen und Bescheid geben, damit wir den Fehler als abgeschlossen markieren können.

**Comment by NicolasSimon99** [comment]
Verantwortlicher Tester: @MarvinGi 
Denk an das Test-System!

**Comment by MarvinGi** [comment]
Umbrüche getestet, passen sich jetzt automatisch an. @JulianeOrt @Lara-u @NicolasSimon99

**Comment by Lara-u** [comment]
@Lilu-S Bitte abschließend Prüfen.

**Comment by Lilu-S** [comment]
@JulianeOrt passt alles, ich schließe es und vermerke das Problem als gelöst.

**Comment by JulianeOrt** [comment]
@MarcinTrojanski bitte in Safari testen, ob die Schriften bei allen Browserfenstern responsiv sind.

**Comment by JulianeOrt** [comment]
<img width="1440" alt="Screenshot 2019-11-07 at 09 57 35" src="https://user-images.githubusercontent.com/36894965/68374905-13d0a200-0146-11ea-9473-76e0c18b826a.png">
Hier ist der Fehler noch vorhanden.

**Comment by MarcinTrojanski** [comment]
@JulianeOrt du musst auf dem Testserver (http://18.197.147.12) immer gucken, da dort die Änderungen vorgenommen werden. Bei mir brechen die Überschriften alle um und es funktioniert einwandfrei bei Safari!

**Comment by NicolasSimon99** [comment]
@MarcinTrojanski ist denn jetzt bereits erfolgreich getestet?

**Comment by JulianeOrt** [comment]
Läuft auf dem Testserver daher schließe ich dieses Issue.
