### ISSUE TITLE
QUZ: Verschiebung der Inhalte, Ansichtsprobleme, Fragen nicht funktionierend

### ISSUE THREAD

**Issue by JulianeOrt** [imbitdhbwma/brillianplatform#29]
Verschiebung der Inhalte, Ansichtsprobleme, Fragen nicht funktionierend beim gesamten Quiz. Die Probleme treten überall auf.

@ErikGarstka, welche Ursache steckt dahinter? Braucht ihr Screenshots von einzelnen Problemen, dann sagt @NicolasSimon99 Bescheid!

**Comment by Lara-u** [comment]
Screenshots um die Probleme zu verdeutlichen wären super @NicolasSimon99!

**Comment by JulianeOrt** [comment]
@Lara-u schau mal hier https://drive.google.com/open?id=11BQiZWlHrRPSA0bh0o6zhSyg_iuvTVVa in den Ordnern 39 und 40.
Ich nehme an, dass der Fehler auf einem Problem basiert, der sich für das ganze Quiz durchzieht, daher zeigen die Screenshots im Grunde alle das gleiche Problem. Aber wie gesagt, wenn ihr noch mehr Beispiele braucht, gebt bescheid!

**Comment by IsabellaMoos** [comment]
Ich hab hier mal das Issue konkretisiert:
[Issue #29 Fehlerbeschreibung.docx](https://github.com/imbitdhbwma/brillianplatform/files/3788925/Issue.29.Fehlerbeschreibung.docx)

**Comment by pnt-linii** [comment]
@Lara-u  @IsabellaMoos  : Irgendwie wurden weitere relevanten Probleme in Issue #39 beschrieben. Ihr könnt da genauer anschauen.

**Comment by pnt-linii** [comment]
> @Lara-u schau mal hier https://drive.google.com/open?id=11BQiZWlHrRPSA0bh0o6zhSyg_iuvTVVa in den Ordnern 39 und 40.
> Ich nehme an, dass der Fehler auf einem Problem basiert, der sich für das ganze Quiz durchzieht, daher zeigen die Screenshots im Grunde alle das gleiche Problem. Aber wie gesagt, wenn ihr noch mehr Beispiele braucht, gebt bescheid!

@JulianeOrt @NicolasSimon99 
Dieses wurde erstmal behoben. Lass uns wissen wenn es euch noch etwas auffällt. 

p/s: Es gibt irgendwie Überschneidung mit Issue #39 ~.~ @JulianeOrt willst du das mal genauer anschauen? Ich denke wir können dieses Issue (mit Drag&Drop Ansichtsfehler) hiermit testen und schließen. Weitere beschriebenen Probleme werden in Issue #39 bearbeiten.

**Comment by Lara-u** [comment]
@pnt-linii ja, ich denke auch das es auf einem gemeinsamen Fehler basiert.

**Comment by Lara-u** [comment]
@NicolasSimon99 bitte einmal testen!

**Comment by NicolasSimon99** [comment]
Erfolgreich unter Chrome, Firefox und Mobil getestet.
@MarcinTrojanski bitte noch am Laptop in Safari testen!

**Comment by MarcinTrojanski** [comment]
Verschieben der Inhalte funktioniert auf allen Apple Endgeräten in Safari bei den getesteten Quizes.

**Comment by NicolasSimon99** [comment]
@JulianeOrt
