### ISSUE TITLE
QUZ: Rechtschreibfehler beheben

### ISSUE THREAD

**Issue by JulianeOrt** [imbitdhbwma/brillianplatform#30]
Rechtschreibfehler im Quiz beheben 

siehe Screenshot-Ordner 44 bis 48
https://drive.google.com/drive/folders/11BQiZWlHrRPSA0bh0o6zhSyg_iuvTVVa?usp=sharing

**Comment by redisa** [comment]
Die Rechtschreibfehler im Quiz wurden behoben. Einige fehler waren inhaltlich. Dafür wurde eine neue Issue erstellt: #38

**Comment by redisa** [comment]
Bitte noch einmal kontrollieren. Die Sachen die in Issue 38 noch bearbeitet werden wurden noch nicht verändert

**Comment by redisa** [comment]
<img width="1427" alt="Screenshot 2019-10-31 at 11 08 29" src="https://user-images.githubusercontent.com/42384635/67938757-6bb05b80-fbd0-11e9-9edf-c9e5acd79601.png">
Die fehlerhafte Darstellung des Links wurde korrigiert (falsche Schriftart).

**Comment by NicolasSimon99** [comment]
@MarvinGi bitte kontollieren und testen.

**Comment by MarvinGi** [comment]
@NicolasSimon99 @JulianeOrt  getestet, funktioniert im Browser. Mobil Android funktioniert nicht.

**Comment by NicolasSimon99** [comment]
@ErikGarstka
