### ISSUE TITLE
CUR: Symbol Quiz verkleinern

### ISSUE THREAD

**Issue by LauraBrinks** [imbitdhbwma/brillianplatform#32]
!Persönlicher Wunsch vom Product Owner!!!
Das Symbol soll etwa so zwei Zeilen Text in Desktop Ansicht, aber nicht unbedingt responsiv :)

![Anmerkung 2019-10-25 123317](https://user-images.githubusercontent.com/56722107/67572023-a2e8bd80-f735-11e9-812b-c9b04c60a38a.png)

**Comment by redisa** [comment]
Wurde erledigt, bitte testen in verschiedenen Browsern und schließen.

**Comment by NicolasSimon99** [comment]
@MarvinGi bitte testen, am Laptop als auch mobil.
@MarcinTrojanski bitte in Safari testen.

**Comment by MarvinGi** [comment]
@NicolasSimon99 Laptop und  (Android) Mobil getestet, alles funktioniert

**Comment by MarcinTrojanski** [comment]
@NicolasSimon99 Safari auf verschiedenen Geräten getestet. Quiz Symbol wird im Vergleich zu vorher kleiner angezeigt.

**Comment by NicolasSimon99** [comment]
@JulianeOrt

**Comment by JulianeOrt** [comment]
vermerkt in Backlog ID36 (07.11.19)
