### ISSUE TITLE
QUZ: Auswertung der einzelnen Fragen anzeigen

### ISSUE THREAD

**Issue by LauraBrinks** [imbitdhbwma/brillianplatform#34]
Wenn ein Quiz ausgewertet wird, wird nicht angezeigt welche Fragen richtig oder falsch beantwortet wurden. Dies ist Laut Product Owner wünschenswert, wurde aber vom Vorgängerkurs nicht mehr geschafft. Die richtigen Antworten sollen mit grün markiert werden, falsche mit rot. 

Laut ihm kann das mit CSS_EIgenschaften lösen (Tip: er meint dazu gibt es ein Youtube Video, CSS lists change bullets oder so)

**Comment by NicolasSimon99** [comment]
@MarvinGi bitte testen, am Laptop und auch mobil.

**Comment by MarvinGi** [comment]
@NicolasSimon99 @ErikGarstka Es werden weder richtige noch falsche Elemente markiert.
Außerdem skalieren die Drag & Drop Elemente nicht und verdecken die anderen Fragen

**Comment by redisa** [comment]
Hallo @DigitaleMedienDHBW,
Wie stellen sie sich die Quiz Auswertung für die verschiedenen Frage Typen vor? Sie hatten vorgeschlagen, die List Bullets zu verändern. Soll das auch für die Drag and Drop Fragen angewendet werden? 
Soll die Auswertung insgesamt die eigenen Angaben mit beinhalten und bewerten oder die allgemeinen Lösungen anzeigen? So wie ich es verstehe, ist es nur, wenn man die allgemeine Lösung angibt möglich, die Bullets z.B. in Kreuze und Haken zu verändern. Wenn die eigenen Antworten beachtet werden sollen, könnte lediglich die Farbe der Bullets in rot und grün verändert werden, sodass die Auswahl sichtbar bleibt. Dabei wäre es jedoch für Menschen mit rot/grün Schwäche notwendig, hinter den jeweiligen Bullet-Point (richtig) oder (falsch) als Text anzuhängen.

**Comment by redisa** [comment]
@NicolasSimon99 Es wurde eine Auswertung eingefügt.
Mit dem Product Owner besprochen werden richtige Antworten in grün und falsche Antworten in grau angezeigt. Bitte testen.
Außerdem wurde die Schriftgröße verkleinert und Textschatten entfernt. Bitte testen, ob die Anzeige in allen Browsern und Mobil richtig angezeigt wird und lesbar ist.

**Comment by MarvinGi** [comment]
Getestet und funktioniert @NicolasSimon99

**Comment by NicolasSimon99** [comment]
@JulianeOrt
