### ISSUE TITLE
Zu beiden Themen existiert keine Literaturliste. @jessilenwell könnt ihr dazu wenn es sinnvoll ist vielleicht noch Literatur heraussuchen?

### ISSUE THREAD

**Issue by jessilenwell** [imbitdhbwma/brillianplatform#37]
Zu beiden Themen existiert keine Literaturliste. @jessilenwell könnt ihr dazu wenn es sinnvoll ist vielleicht noch Literatur heraussuchen?

> Unter Curriculum, WI, Integrationsseminar wird keine Literaturliste angezeigt wenn oben rechts auf Integrationsseminar geklickt wird. Bei WI, Fallstudie tritt das gleiche Problem auf. Ist das ein Fehler im Code oder existiert hier keine Literaturliste? Wenn nicht dann bitte ans PM-Team wenden!
> ![Anmerkung 2019-10-26 175123](https://user-images.githubusercontent.com/56722107/67622442-765aa180-f81a-11e9-84da-d9e420958935.png)
> ![Anmerkung 2019-10-26 175227](https://user-images.githubusercontent.com/56722107/67622444-7c508280-f81a-11e9-9e7e-bd2b2e1cce8f.png)

_Originally posted by @redisa in https://github.com/imbitdhbwma/brillianplatform/issues/21#issuecomment-546633042_

**Comment by DigitaleMedienDHBW** [comment]
Hallo Frau Lenwell,

die Literaturliste in den Modulbeschreibungen des Curriculums - Spalte rechts, die bei Klick/Touch auf den Modulnamen aufklappt - enthält die Literatuiremphelumngen in der offiziellen Modulbeschreibung. Da ändern wir bitte nichts eigenmächtig; zum Integrationsseminar und zur Fallstudie gibt es tatsächlich keine Literaturempfehlungen.

Die Angaben zu den Digital Learning Quellen in der rechten Spate dürfen wir nach Belieben aktualisieren oder anpassen - aber bitte in Rücksprache mit dem Product Owner und ggfs. einem unserer Dozenten, der das betreffende Modul liest.

Mit freundlichen Grüßen 
Prof. Peter Mayr
