### ISSUE TITLE
QUZ: Inhalt korrigieren

### ISSUE THREAD

**Issue by redisa** [imbitdhbwma/brillianplatform#38]
Einige Fragen im Quiz waren inhaltlich fehlerhaft. 
Daher bitte folgendes erledigen:

- Screenshot 46 (https://drive.google.com/drive/folders/11BQiZWlHrRPSA0bh0o6zhSyg_iuvTVVa?usp=sharing) alternative Antwortmöglichkeiten ausarbeiten

- Screenshot 45,3 und 45,4 richtige Antworten überprüfen

- Screenshot 44,2 alternative Antwortmöglichkeiten erstellen

**Comment by jessilenwell** [comment]
@redisa Screenshot 46 
Innenfinanzierung = Abschreibung, Rückstellungen, Kapitalfreisetzung
Fremdfinanzierung = Anleihen, Darlehen, Liferantenkredit

**Comment by jessilenwell** [comment]
@redisa 
also zu 45: 
Human Resource= Buchhaltung, Controlling, Personalbeurteilung, Mahnwesen 

Technology Development = Produktentwicklung, Entwicklung Verfahrenstechnik, SW-Entwicklung für die Produktion 

Procurement = Lieferantenauswahl, Preisverhandlung, Facility Management, Abschluss Rahmenvertrag

**Comment by jessilenwell** [comment]
@redisa  Frage "Ordne die folgenden Tätigkeiten den Primäraktivitäten zu." : 

also mit den Antwortmöglichkeiten die bereits vorhanden sind, würde ich auf diese Lösung kommen: 
[BWlQuizz.pdf](https://github.com/imbitdhbwma/brillianplatform/files/3847815/BWlQuizz.pdf)


ABER, wenn es möglich ist andere Antwortmöglichkeiten zu nehmen würde ich folgendes vorschlagen (was ich besser finde): 

Operations = Auftragsannahme, Inventur, Wartung 
Outbound Logistics= Verpackung, Zwischenlagerung, Kommissioierung, Monatge
Marketing= Promotion, Preispolitik, Externe und Interne Kommunikation

**Comment by redisa** [comment]
@NicolasSimon99 es wurden alle fehler die wir finden konnten behoben. Bitte diese Fehler testen und andere Fehler melden, falls ihr noch etwas findet. Danke!

**Comment by NicolasSimon99** [comment]
@MarvinGi bitte testen. (Chrome und Edge)
@MarcinTrojanski bitte in Safari und mobil testen.

**Comment by MarvinGi** [comment]
Chrome & Edge getestet

**Comment by linafodi** [comment]
@MarcinTrojanski wurde das getestet?

**Comment by MarcinTrojanski** [comment]
@linafodi ja funktioniert alles auf den 3 Apple Geräten in Safari!
