### ISSUE TITLE
Lernvideos: Responsive Darstellung der videos

### ISSUE THREAD

**Issue by pnt-linii** [imbitdhbwma/brillianplatform#40]
Videos werden komisch angezeigt auf kleinerer Auflösung --> CSS Anpassung für iframe/embedded videos.

**Comment by pnt-linii** [comment]
Added div around iframe for better display of videos.

**Comment by pnt-linii** [comment]
Updated videos source links in dnSlide.js (TODO des Vorgängigen Kurses)

**Comment by pnt-linii** [comment]
Videos reponsiv gemacht.
Vorher:
![image](https://user-images.githubusercontent.com/56722146/67846173-0ccfe100-fb01-11e9-9168-a5be65ca4ee4.png)

Nachher:
![image](https://user-images.githubusercontent.com/56722146/67846213-18230c80-fb01-11e9-9fe1-03e8cb25102a.png)

**Comment by pnt-linii** [comment]
@NicolasSimon99 bitte testen

**Comment by NicolasSimon99** [comment]
@StevenHerrenknecht bitte testen. (in allen Browsern)
@MarcinTrojanski bitte in Safari testen.

**Comment by StevenHerrenknecht** [comment]
@NicolasSimon99 In Edge und Chrome getestet. Videos werden wie gewünscht dargestellt.
@MarcinTrojanski könntest du, wenn Safari auch wie gewünscht funktioniert, gerade den kompletten Issue an Design assignen, bevor wir jetzt getrennt einmal Chrome und Safari getrennt voneinander weitergeben? Danke!

**Comment by Lilu-S** [comment]
@pnt-linii wäre es möglich, das automatische Durchlaufen der Videos im Browser Firefox anzupassen? Dort sind die Videos momentan noch starr.

**Comment by MarcinTrojanski** [comment]
@NicolasSimon99 alle Videos auch in Safari responsiv. Kann dann an Design assigned werden 👍🏼

**Comment by Lilu-S** [comment]
@JulianeOrt ich schließe das Issue somit. Firefox sollen wir erst einmal außen vor lassen.
