### ISSUE TITLE
CUR: Inhalt der alten Webseite integrieren

### ISSUE THREAD

**Issue by redisa** [imbitdhbwma/brillianplatform#43]
Bitte ausarbeiten wo und mit welchem Text folgende Dateien eingearbeitet werden können:

[IMBIT_Research_Methods_Schuster.pdf](https://github.com/imbitdhbwma/brillianplatform/files/3788432/IMBIT_Research_Methods_Schuster.pdf)
[Vorlage_fuer_Posterpraesentation.pptx](https://github.com/imbitdhbwma/brillianplatform/files/3788442/Vorlage_fuer_Posterpraesentation.pptx)
[IMBIT_Erstsemesterinfos.pdf](https://github.com/imbitdhbwma/brillianplatform/files/3788443/IMBIT_Erstsemesterinfos.pdf)

Die Inhalte der ehemaligen IMBIT Webseite findet ihr [hier](https://drive.google.com/drive/folders/12nFdS_5HXYat-frWJyWSl-jwjBQ20ArW). Was wollen wir davon nutzen? Die Webarchive Files lassen sich nur mit Safari öffnen.

**Comment by linafodi** [comment]
Ich kann auf die Inhalte der alten Website über den Link leider nicht zugreifen, kann mir die jemand anders zukommen lassen? @redisa 
![Bildschirmfoto 2019-11-10 um 10 58 26](https://user-images.githubusercontent.com/56722126/68542141-83929700-03a9-11ea-8e3b-8a2ad8e8f64f.png)

**Comment by linafodi** [comment]
Auch wenn ich das Öffnen trotzdem zulasse, wird mir kein Inhalt angezeigt..

**Comment by juliaschmatolla** [comment]
**IMBIT_Research_Methods_Schuster.pdf**
Ort: Grundlagen wissenschaftlicher. Arbeiten 

Dieses Dokument ist eine Ergänzung zum Leitfaden des wissenschaftlichen Arbeitens, hier können Vorgehensweisen, Methoden und Tipps zum Erststellen wissenschaftlicher Arbeiten nach gelesen werden.
This document is a supplement to the Guide to Scientific Work, where you can read procedures, methods and tips for writing scientific papers.

**Comment by linafodi** [comment]
@juliaschmatolla das könnte man vielleicht im Curriculum zu Schlüsselqualifikation II - Wissenschaftliches Arbeiten einarbeiten? (siehe #51)

**Comment by juliaschmatolla** [comment]
**Vorlage_fuer_Posterpraesentation.pptx**
Ort: Grundlagen wissenschaftlicher. Arbeiten, http://www.brillianideas.com/index.html

Die Vorlage der Posterpräsentation, dient als Unterstützung und Umsetzungshilfe für das Erarbeiten, einer Posterpräsentation, die insbesondere für die Vorbereitung der Bachelor Skizze notwendig ist.
The poster presentation template serves as support and implementation aid for the development of a poster presentation, which is particularly necessary for the preparation of the Bachelor sketch.

**Comment by juliaschmatolla** [comment]
**IMBIT_Erstsemesterinfos.pdf**
Ort: Am liebsten Curriculum ?

In komprimierter Form findet man hier die Antworten auf die häufigst gestellten Fragen. 
Here you will find the answers to the most frequently asked questions in condensed form.

**Comment by linafodi** [comment]
Ideen zum Einfügen der Inhalte der alten Website:
- **Projekte**: 
    - Entweder sortieren und jeweils im curriculum an der jeweiligen stelle 
    - oder Im Digital Learning einen Punkt mit „Projekte“ 
- **News & Events**: unter Imbit Curriculum neuer Reiter mit News & Events 

**!!Muss erst mit Prof. Mayr besprochen werden!!**

**Comment by pnt-linii** [comment]
> **IMBIT_Research_Methods_Schuster.pdf**
> Ort: Grundlagen wissenschaftlicher. Arbeiten
> 
> Dieses Dokument ist eine Ergänzung zum Leitfaden des wissenschaftlichen Arbeitens, hier können Vorgehensweisen, Methoden und Tipps zum Erststellen wissenschaftlicher Arbeiten nach gelesen werden.
> This document is a supplement to the Guide to Scientific Work, where you can read procedures, methods and tips for writing scientific papers.

@IsabellaMoos @Lara-u

**Comment by juliaschmatolla** [comment]
Ergänzungstext für IMBIT_Research_Methods_Schuster.pdf:

Dieses Dokument ist eine Ergänzung zu den Richtlinien für wissenschaftliches Arbeiten, spezialisiert auf den Studiengang IMBIT. Es enthält Vorgehensweisen, Forschungsmethoden (Folie 52ff.), Informationen zur Literaturrecherche (Folie 64ff.), Referenzstile (Folie 78ff.) und Tipps zum Erststellen wissenschaftlicher Arbeiten nach gelesen werden.

This document is a supplement to the guidelines for scientific work, specialized in the IMBIT course of studies. It contains procedures, research methods (Slide 52 cff.), best ways for literature search (Slide 64 cff.), styles of referencing (Slide 78 cff.) and tips for the first presentation of scientific work.

**Comment by Lara-u** [comment]
Added: IMBIT_Research_Methods_Schuster.pdf
Ort: Grundlagen wissenschaftlicher. Arbeiten

**Comment by Lara-u** [comment]
bitte Testen (IMBIT_Research_Methods_Schuster.pdf
Ort: Grundlagen wissenschaftlicher. Arbeiten) @NicolasSimon99

**Comment by NicolasSimon99** [comment]
Erfolgreich getestet.
@JulianeOrt
