### ISSUE TITLE
ICM: Mailfunktion

### ISSUE THREAD

**Issue by Myprr** [imbitdhbwma/brillianplatform#44]
Ein game zuende spielen um am ende Badge zu bekommen.
die Badges sollen per mail versendet werden.
bitte testen ob die mail ankommt.
Hier der link: http://brillianideas.com:8080/brillianICM/
registrierung vorausgesetzt soll auch funktionieren

**Comment by JulianeOrt** [comment]
Hey @NicolasSimon99 könnt ihr eines der Spiele (CRM oder ICM) bis zum Ende durchspielen? vorher müsst ihr euch noch registrieren

**Comment by NicolasSimon99** [comment]
@StevenHerrenknecht bitte einmal testen...Laptop und Mobil.

**Comment by StevenHerrenknecht** [comment]
@Myprr @Technik @NicolasSimon99  Ich kann mich leider nicht im ICM Spiel registrieren, bzw. bekomme nach der Eingabe meiner Daten keinen Aktivierungslink zugesendet. Bevor das nicht behoben ist kann ich leider nicht das Spiel durchspielen und damit testen.

**Comment by Myprr** [comment]
Erstmal **on hold** bis wir das Registrirungsproblem gelöst haben.

**Comment by StevenHerrenknecht** [comment]
Kann auch nicht mit dem Standarduser student@brillianicm und dem ausgeteilten Passwort getestet werden...
Lediglich Zugriff über Adminlogin möglich

**Comment by Myprr** [comment]
Registrierungsproblem ist behoben.

Bitte das Spiel durchspielen um am Ende das Zertifikati per Mail zu bekommen.

**Comment by StevenHerrenknecht** [comment]
@Myprr Weder auf dem Testserver, noch auf dem momentanen Produktivserver funktioniert die Registrierung bei ICM. Im Produktivsystem wird mir nach dem ich auch "Register" geklickt habe folgendes angezeigt:
![image](https://user-images.githubusercontent.com/56722211/69044578-70a94380-09f5-11ea-9a36-ab473d7fe3e0.png)

Wenn ich mich im Test registrieren möchte, bekomme ich keine EMail zugesendet.

**Comment by StevenHerrenknecht** [comment]
@Myprr Getestet auf Chrome: Registrierung funktioniert, wie bei CRM, nun einwandfrei...
Allerdings bekomme ich am Ende kein Zertifikat per Mail zu gesendet...
![image](https://user-images.githubusercontent.com/56722211/69743774-4e26d100-113f-11ea-85f2-07dfb6190363.png)

Das ist doch das Ende, oder übersehe ich etwas?

**Comment by StevenHerrenknecht** [comment]
Noch ein Fehler, der mir beim durchspielen von ICM aufgefallen ist:
![image](https://user-images.githubusercontent.com/56722211/69744149-ecb33200-113f-11ea-839c-9b86d6d30a4d.png)

Man muss die Vereine an die richtige Position ziehen, allerdings werden diese nicht im Drag und Drop dargestellt... @JulianeOrt würdest du bitte ienen neuen Issue erstellen, oder wie wird das geregelt?

**Comment by JulianeOrt** [comment]
> @Myprr Getestet auf Chrome: Registrierung funktioniert, wie bei CRM, nun einwandfrei...
> Allerdings bekomme ich am Ende kein Zertifikat per Mail zu gesendet...
> ![image](https://user-images.githubusercontent.com/56722211/69743774-4e26d100-113f-11ea-85f2-07dfb6190363.png)
> 
> Das ist doch das Ende, oder übersehe ich etwas?

@Myprr könntest du mal schauen, wie genau die Zertifizierungs-Funktion mit der Mailfunktion zusammen hängt? Meinem Verständnis nach sollte es bei CRM funktionieren - bei ICM allerdings aber noch nicht. Dann müssen wir das noch anpassen.

**Comment by Myprr** [comment]
@JulianeOrt ich schaue mal. Die große Frage ist ob bei ICM überhaupt am Ende des Spiels etwas verschickt werden soll. (?)

**Comment by JulianeOrt** [comment]
> @JulianeOrt ich schaue mal. Die große Frage ist ob bei ICM überhaupt am Ende des Spiels etwas verschickt werden soll. (?)

Ja das soll es.

**Comment by JulianeOrt** [comment]
> @Myprr Weder auf dem Testserver, noch auf dem momentanen Produktivserver funktioniert die Registrierung bei ICM. Im Produktivsystem wird mir nach dem ich auch "Register" geklickt habe folgendes angezeigt:
> ![image](https://user-images.githubusercontent.com/56722211/69044578-70a94380-09f5-11ea-9a36-ab473d7fe3e0.png)
> 
> Wenn ich mich im Test registrieren möchte, bekomme ich keine EMail zugesendet.

@Myprr was ist mit diesem Problem?

**Comment by Myprr** [comment]
> 
> 
> > @Myprr Weder auf dem Testserver, noch auf dem momentanen Produktivserver funktioniert die Registrierung bei ICM. Im Produktivsystem wird mir nach dem ich auch "Register" geklickt habe folgendes angezeigt:
> > ![image](https://user-images.githubusercontent.com/56722211/69044578-70a94380-09f5-11ea-9a36-ab473d7fe3e0.png)
> > Wenn ich mich im Test registrieren möchte, bekomme ich keine EMail zugesendet.
> 
> @Myprr was ist mit diesem Problem?

Offensichtlich wurde es in einem anderen issue behoben, sonst könnte Steven sich nicht registrieren.
Dieses Issue kann abgeschloßen werden, da nun die Mailfunktion bei ICM wieder aktiv ist.
