### ISSUE TITLE
Port :8080 Verlinkungsproblem

### ISSUE THREAD

**Issue by ErikGarstka** [imbitdhbwma/brillianplatform#45]
"Q" icon/picture Verlinkung zu :8080 port funktioniert nicht. Link über Text "IT-Intro Quiz" funktioniert!

![Capture1.PNG](https://images.zenhubusercontent.com/5da995a0e252b50001ba2d32/7bf9de56-e718-48d2-8d3d-af94e54d22ea)

**Comment by ErikGarstka** [comment]
IMBIT Curriculum > Informatik > Grundlagen der IT

**Comment by ErikGarstka** [comment]
@NicolasSimon99 tested grad ob der Link über dem markierten Bild funktioniert

**Comment by redisa** [comment]
Der gleiche Fehler tritt hier auf:
Von der Startseite/Curriculum/Digital Learning Seite kann über den Launchbar auf die Lernvideos BWL und das Impressum zugegriffen werden (http://18.197.147.12/LernvideosBWL.html). Vom Quiz aus führt es zu http://18.197.147.12:8080/LernvideosBWL.html auf dem Testserver und somit Page not found.

**Comment by NicolasSimon99** [comment]
@NicolasSimon99 ich teste in Chrome und Edge
@MarcinTrojanski bitte in Safari und Mobil testen.

**Comment by najann** [comment]
wie Isabell schon festgestellt hat war das bei IT intro kein Einzelfall. Zumal nach Eriks fix zwar das Bild, dafür aber nicht mehr die Schrift funktioniert hat. Hab das jetzt bei allen anderen Quizzen, wo Schrift & Bild auf dasselbe verlinken soll auch gefixt.

**Comment by najann** [comment]
Das vom quiz aus müsste jetzt auch laufen :)

**Comment by NicolasSimon99** [comment]
Unter Edge, Chrome und Firefox funktionieren alle Verlinkungen aus dem Curriculum in die Quizze.

**Comment by MarcinTrojanski** [comment]
Bei Safari funktioniert es jetzt auch einwandfrei!

**Comment by NicolasSimon99** [comment]
@JulianeOrt
