### ISSUE TITLE
INF: kleine Details im Impressum

### ISSUE THREAD

**Issue by JulianeOrt** [imbitdhbwma/brillianplatform#46]
- Responsivität durch Margin-left und Margin-right je 25% - gibt es eine bessere Einstellung, denn so wird viel Platz frei gelassen. (vor allem mobile Ansicht)
- ist ein direkter Link zu Impressum notwendig? / Navigation zum Impressum von anderen Seiten/Unterseiten notwendig? 
- Muss eine Telefonnummer vorhanden sein? 

@ErikGarstka kannst du das mit Tobias absprechen? Er hatte die Anmerkungen gemacht. 
Ansonsten müssen wir Herr Mayr fragen, wie notwendig die Änderungen sind.

**Comment by dfg42** [comment]
Please assign.

**Comment by dfg42** [comment]
@JulianeOrt @ErikGarstka 
Laut Gesetz muss das Impressum „leicht erkennbar, unmittelbar erreichbar und ständig verfügbar“ sein. Ich schlage auch vor das Impressum nach aktuellem Standard neu zu erstellen, hierfür bietet sich der Impressum Generator von eRecht24 an.

**Comment by dfg42** [comment]
[impressum.pdf](https://github.com/imbitdhbwma/brillianplatform/files/3818883/impressum.pdf)

**Comment by JulianeOrt** [comment]
@dfg42 klärst du die Änderung mit dem PO ab oder soll ich das übernehmen?

**Comment by JosieRuehling** [comment]
Hallo zusammen, 

das Impressum wird bitte nur um den entsprechenden Artikel durch das Marketing-Team ergänzt. 
Es muss kein neues Impressum erstellt werden. @JulianeOrt @ErikGarstka @dfg42 

Diese zwei Sachen wurden vom PO zusätzlich vorgeschlagen: 

— In der Launchbar könnten wir das Piktogramm zwischen dem jetzigen einzelnen I und dem Wort Impressum changieren lassen.
— Im Text erwähnen wir inzwischen so viele Kurse, dass wir die einzelnen Absätze auf die Überschrift kollabieren lassen könnten, die dann erst bei Touch/Klick expandieren. Wie wäre es mit einem Vorschlag oder Prototyp, wie man das mit HTML/CSS geschickt realisiert?

**Comment by JulianeOrt** [comment]
> Hallo zusammen,
> 
> das Impressum wird bitte nur um den entsprechenden Artikel durch das Marketing-Team ergänzt.
> Es muss kein neues Impressum erstellt werden. @JulianeOrt @ErikGarstka @dfg42
> 
> Diese zwei Sachen wurden vom PO zusätzlich vorgeschlagen:
> 
> — In der Launchbar könnten wir das Piktogramm zwischen dem jetzigen einzelnen I und dem Wort Impressum changieren lassen.
> — Im Text erwähnen wir inzwischen so viele Kurse, dass wir die einzelnen Absätze auf die Überschrift kollabieren lassen könnten, die dann erst bei Touch/Klick expandieren. Wie wäre es mit einem Vorschlag oder Prototyp, wie man das mit HTML/CSS geschickt realisiert?

@dfg42 bitte das Impressum wie gehabt lassen und stattdessen Gedanken über die oben genannten Anmerkungen machen.

**Comment by ErikGarstka** [comment]
@dfg42 Bitte ein Dropdown Menü mit den Kursen erstellen, wobei der erste und neuste Kurs geöffnet angezeigt wird

**Comment by dfg42** [comment]
@JulianeOrt @ErikGarstka 
Prototyp steht:

![grafik](https://user-images.githubusercontent.com/28921157/68937531-d51d9600-079c-11ea-8d06-fa131921de85.png)

**Comment by dfg42** [comment]
Commit zu dev hat stattgefunden. Es fehlt noch das aktuelle Impressum vom Marketing, dann kann ich es final machen.
Habe des Weiteren noch die impressum.html Datei generell bereinigt.

**Comment by JulianeOrt** [comment]
@dfg42 kannst du nochmal bzgl. der Launchbar schauen? Die sieht aktuell so aus auf dem Testserver.
<img width="85" alt="Screenshot 2019-11-21 at 14 14 10" src="https://user-images.githubusercontent.com/36894965/69341121-3c3dbd80-0c69-11ea-9e74-59188d928fcc.png">

**Comment by dfg42** [comment]
@JulianeOrt konnte noch keine Lösung finden, Erik ist gerade noch dran was daran generell zu verbessern. Vielleicht wird es dadurch behoben.

**Comment by JosieRuehling** [comment]
Hallo zusammen,

zum Impressum: Das Anzeigen und Verschwinden lassen der Kursinfos ist zu kompliziert geworden: Warum ein eigener Knopf "IT Projekt Frühjahr 2019 – WIMBIT16C" der beim Betätigen eine Überschrift "IT Projekt Frühjahr 2019 – WIMBIT16C" mit Bild und Text aufklappt? (also dann zweimal der Text "IT Projekt Frühjahr 2019 – WIMBIT16C" hintereinander) Nehmen Sie die bisherige Lösung mit den einzelnen Kursbeschreibungen als Listenlemente, bei denen die Überschrift des zweiten und aller weiteren Listenelemente als aktive Flächen zum Anzeigen und Verschwinden dienen.

Mit freundlichen Grüßen 
Prof. Peter Mayr 

**@dfg42 Bitte beachten!!!**

**Comment by dfg42** [comment]
@JulianeOrt @JosieRuehling @ErikGarstka 
Bitte Ticket #42 beachten.
