### ISSUE TITLE
LRN: Hintergrund fehlend

### ISSUE THREAD

**Issue by JulianeOrt** [imbitdhbwma/brillianplatform#47]
- In Safari fehlt der Hintergrund/die Seite
<img width="1440" alt="Screenshot 2019-10-31 at 16 40 09" src="https://user-images.githubusercontent.com/36894965/67962403-57cf1e80-fbfd-11e9-9918-7745bbbe034d.png">

**Partly FIXED**
das problem hier ist nicht, dass der Hintergrund fehlt, sondern dass in sehr seltenen fällen direkt auf die Datei `curriculum.html` bzw. `digitalLearning.html`verlinkt wird, statt deren content in `Index.html` zu laden. Dadurch fehlen da dann ein paar JS&CSS-links. 
Warum das Laden manchmal nicht funktioniert, ist genauso undurchschaubar wie bei dem Menü-Krakenarm... Das primäre Darstellungproblem ist aber vorerst gelöst.

**Comment by JulianeOrt** [comment]
- Chrome: Ausrichtung der gesamten Seite komplett verschoben, rauszoomen passt das Fenster nicht an, Pop Up Fenster, die weitere Informationen anzeigen sind nach oben verschoben. Überschrift wird nicht bzw. nur zur Hälfte angezeigt...

**Comment by JulianeOrt** [comment]
Chrome: Unter dem Punkt Spiel, kann man auf das Quiz-Bild klicken welches einen zu anderern Quizzen als in der Lauchbar weiterleitet, bei diesen fehlen Überschriften und teilweise überdecken Überschriften auch den Beschreibungtext.

**Comment by JulianeOrt** [comment]
Safari: Podcast 2.Bild. Link bei dem 2.Bild funktioniert nicht
@MarcinTrojanski, welcher Link soll verwendet werden?/Worauf soll verwiesen werden (Anmerkung kam laut Excel von dir)

**Comment by redisa** [comment]
> Chrome: Unter dem Punkt Spiel, kann man auf das Quiz-Bild klicken welches einen zu anderern Quizzen als in der Lauchbar weiterleitet, bei diesen fehlen Überschriften und teilweise überdecken Überschriften auch den Beschreibungtext.

Hier wird inzwischen auf das gleiche Quiz wie vom Launchbar aus verlinkt.

**Comment by MarcinTrojanski** [comment]
> Safari: Podcast 2.Bild. Link bei dem 2.Bild funktioniert nicht
> @MarcinTrojanski, welcher Link soll verwendet werden?/Worauf soll verwiesen werden (Anmerkung kam laut Excel von dir)

http://biz-anthro.com/index.php/podcasts/  dieser Link geht nicht bei Podcasts. 
Mein Vorschlag: einfach weg machen - bzw. https://player.fm/featured/anthropology diesen Link anbieten, dann müsste jedoch der Text verändert werden.
@DigitaleMedienDHBW oder haben Sie dazu noch etwas?

**Comment by JulianeOrt** [comment]
> * Chrome: Ausrichtung der gesamten Seite komplett verschoben, rauszoomen passt das Fenster nicht an, Pop Up Fenster, die weitere Informationen anzeigen sind nach oben verschoben. Überschrift wird nicht bzw. nur zur Hälfte angezeigt...
> 
> **EDIT:**
> modal (pop-up) Fehler sind behoben
> 
> @JulianeOrt Gibt es für den rest screenshots oder so? Kann es nicht nachvollziehen

@StevenHerrenknecht folgende Aussagen sind von dir: "_Ausrichtung der gesamten Seite komplett verschoben, rauszoomen passt das Fenster nicht an_" & "_Pop Up Fenster, die weitere Informationen anzeigen sind nach oben verschoben. Überschrift wird nicht bzw. nur zur Hälfte angezeigt..._"
Könntest du bitte Screenshots anhängen, damit der Fehler ersichtlich wird?

**Comment by StevenHerrenknecht** [comment]
@JulianeOrt  Wo hab ich das geschrieben? Sei so gut und schick mir mal einen Link von der entsprechenden Stelle. 
Sonst wird es schwer für mich zuzuordnen bei welchem Teil der Fehler aufgetreten ist, bei der Fülle an Anzeigefehlern.

**Comment by JulianeOrt** [comment]
@StevenHerrenknecht in der Excel-Liste

**Comment by StevenHerrenknecht** [comment]
@najann @JulianeOrt EDIT: Der Punkt war auf das Untermenü "Digitales Lernen" bezogen, wo die Mindmap nicht angepasst wird auf die Ansicht von mobilen Endgeräten. Screenshots davon gibt es ja bereits, deshalb hänge ich nicht nochmal einen an. Da, meine ich, Herr Mayr die mobilen Endgeräte erstmal hinten anstellen will, kann der Kommentar vorerst ignoriert werden.

**Comment by JulianeOrt** [comment]
werde mit dem Product Owner absprechen, in wie weit die Responsivität für den Punkt LRN gegeben sein muss.

**Comment by najann** [comment]
also ich sehe jetzt hier noch als offen an: 
der Podcast link für anthropology und die responsivität fürs grid. 
@JulianeOrt welche Lösungen sollen für beides verwendet werden?

**Comment by JulianeOrt** [comment]
@najann die Responsivität für mobil kann außen vorgelassen werden, da es im Querformat ausreichend ist.

**Comment by JulianeOrt** [comment]
> also ich sehe jetzt hier noch als offen an:
> der Podcast link für anthropology und die responsivität fürs grid.
> @JulianeOrt welche Lösungen sollen für beides verwendet werden?

Für den Podcast wurde ein neues Issue geöffnet. Die Responsivität kann außen vorgelassen werden, daher schließe ich das Isssue.
