### ISSUE TITLE
STR: Luftblasen auf unbegrenzte Zeit

### ISSUE THREAD

**Issue by Lilu-S** [imbitdhbwma/brillianplatform#48]
Die Luftblasen auf der Startseite hören nach einiger Zeit auf hochzusteigen. Kann man dies auf unbegrenzte Zeit einstellen? Wenn ja, bitte anpassen.

**Comment by dfg42** [comment]
@Lilu-S @ErikGarstka 
Zunächst mal zur Information: Es handelt sich um eine Video das in einem Loop läuft - es gibt aus meiner sicht zwei Möglichkeiten: 
1. Wir analysieren warum der Loop nach einer gewissen Zeit aufhört zu laufen --> vermutlich lässt sich das durch einen einfachen Reload der Seite lösen. Da es sich um die Startseite handelt sollte da keine Probleme verursachen.
2. Wir versuchen meinen Vorschlag von Issue #33 auf der gesamten Seite zu implementieren.

**Comment by JulianeOrt** [comment]
@dfg42 was ist der Status? Wird das Problem bis Sprintende gelöst?

**Comment by ErikGarstka** [comment]
Problem von PO als unwichtig deklariert
