### ISSUE TITLE
CUR: Sichtbarer Bereich anpassen

### ISSUE THREAD

**Issue by LauraBrinks** [imbitdhbwma/brillianplatform#49]
Ursprüngliche Analyse: "beim verkleinern des Fensters wird der Sichtbereich eingeschränkt (andere Auswahlmöglichkeiten verschwinden, keine scroll funktion)".
Ich konnte es mit Chrome nicht nachvollziehen, könntet ihr das nochmal mit Safari testen?

**Comment by MarcinTrojanski** [comment]
<img width="1440" alt="Bildschirmfoto 2019-11-05 um 11 09 44" src="https://user-images.githubusercontent.com/56722421/68198694-d68cd880-ffbc-11e9-83e6-3c80aed15ef6.png">
@ErikGarstka wenn ich im Curriculum bin zeigt der mir auf dem Testserver nicht alle Auswahlmöglichkeiten an und scrollen kann ich nicht!

**Comment by ErikGarstka** [comment]
Problem behoben

**Comment by JulianeOrt** [comment]
@MarcinTrojanski ist der Test erfolgreich?

**Comment by JulianeOrt** [comment]
https://github.com/imbitdhbwma/brillianplatform/issues/62#issuecomment-553832371

bitte Fehler beheben @ErikGarstka

**Comment by ErikGarstka** [comment]
Issue ist laut PO kein für uns relevantes Problem
