### ISSUE TITLE
CUR: "Hier gehts zurück" Link funktioniert nicht

### ISSUE THREAD

**Issue by LauraBrinks** [imbitdhbwma/brillianplatform#50]
Der Link "Hier gehts zurück" funktiert mpbil und mit Chrome nicht. Mit Safari angeblich schon. Man erreicht die Seite über das Hier gehts zu Quiz unter Curriculum, IT, Datenbanken. 

![Anmerkung  2019-11-02 212410](https://user-images.githubusercontent.com/56722107/68076608-2306c700-fdb7-11e9-8501-9d17021f3c15.png)

**Comment by najann** [comment]
dürfte jetzt funktionieren :)

**Comment by NicolasSimon99** [comment]
Erfolgreich getestet.

**Comment by JulianeOrt** [comment]
In Backlog vermerkt (4.11.19)
