### ISSUE TITLE
CUR: Inhalte fehlen

### ISSUE THREAD

**Issue by LauraBrinks** [imbitdhbwma/brillianplatform#51]
Im Curriculum fehlen auf einigen Seiten links Inhalte. 
Explizit genannt wurden in der Analyse die Schlüsselqualifikationen (II und III), Global Project Management und Dienstleistungsmanagement. Aber es gibt auch noch andere Seiten auf denen nur ein oder zwei Einträge vorhanden sind, vielleicht sollte man da auch noch was hinzufügen.
![Anmerkung 2019-11-02 212410](https://user-images.githubusercontent.com/56722107/68076687-4120f700-fdb8-11e9-83d6-0015bc8132f4.png)

**Comment by juliaschmatolla** [comment]
**SW-Lifecycle**
https://de.coursera.org/learn/software-processes
Der Software-Lebenszyklus bezieht sich auf alle Phasen eines Softwareprodukts von der Planung, Entwicklung und Nutzung bis hin zur Außerbetriebnahme.
 In diesem Kurs erhalten Sie einen Überblick darüber, wie Software-Teams funktionieren; Welche Prozesse genutzt werden;  Was sind branchenüblichen Methoden? Was sind die Vor- und Nachteile?

The software life cycle refers to all phases of a software product from planning, development and use to obsolescence or decommissioning.
 In this course,  you will get an overview of  how software teams work? What processes they use?  What are some of the industry standard methodologies? What are pros and cons of each?

**Comment by linafodi** [comment]
**Schlüsselqualifikationen II - Wissenschaftstheorie und wissenschaftliche Methoden der Wirtschaftsinformatik**
https://iversity.org/de/courses/wissenschaftliches-denken-arbeiten-und-schreiben-march-2016
Der Online-Kurs „Wissenschaftliches Denken, Arbeiten und Schreiben“ der Fachhochschule Münster vermittelt alle Grundtechniken wissenschaftlichen Arbeitens von Zitation bis Datenerhebung. Es wird dabei auch über Lerntypen und Arbeitsorganisation gesprochen.“ 


https://ilias.uni-halle.de/ilias.php?ref_id=61583&cmd=render&cmdClass=ilrepositorygui&cmdNode=ue&baseClass=ilrepositorygui
Dieser Selbstlernkurs der Universität Halle-Wittenberg erklärt wissenschaftliche Denkweisen und gibt Hilfestellungen in Bezug auf die Anfertigung einer wissenschaftlichen Arbeit. Aktuell stehen die Lernmodule „Wissenschaftliches Denken & Arbeiten“, „Grundlagen des Urheberrechts“, „Planung & Vorbereitung der wissenschaftlichen Arbeit“, „Orientierung, Verwaltung & Dokumentation“ und „Präsentation & Visualisierung“ zur Verfügung. Die Module könne separat und unabhängig voneinander bearbeitet werden und nehmen zwischen 80 und 120 Minuten in Anspruch

**Comment by linafodi** [comment]
**Schlüsselqualifikation III - Unternehmenssimulation**

Planspiel Wein 
http://www.planspielw.de/Welcome.aspx
In diesem Planspiel übernehmen Sie die Leitung eines Unternehmens, das Trauben einkauft, diese zu Wein verarbeitet und anschließend auf dem Markt anbietet. Wie in einem richtigen Unternehmen übernehmen Sie Kontrolle über die Bereiche Einkauf, Produktion, Vertrieb, Marketing, Personal und Finanzierung. Mit Ihren Entscheidungen müssen Sie sich gegen mehrere Konkurrenten am gleichen Markt durchsetzen und am Ende der Simulation einen möglichst hohen Marktwert Ihres Unternehmens erzielen

**Comment by JosieRuehling** [comment]
**Global Project Management Skills**

International Project Management 
https://www.edx.org/course/international-project-management-3
In diesem Kurs werden die Auswirkungen auf das Projektmanagement von Kultur, Sprachvariationen, religiösen, regulatorischen und rechtlichen Praktiken, Technologiepenetration, zeitlicher Orientierung, Geschlechterfragen, Korruption, Ethik, persönlicher Freiheit und politischen Kontexten untersuchrt. Es wird gelernt, wie die Herausforderungen globaler Projekte durch den effizienten Einsatz von Praktiken und Technologien bewältigen werden können. Der Kurs nutzt verfügbare Fallstudien und Beispiele aus Unternehmen, um den Studenten zu helfen, die Fähigkeiten zu verbessern, die sie benötigen, um ein erfolgreiches internationales Projektumfeld zu erkennen und zu fördern.

International Project Management and Future of Work
https://www.oncampus.de/weiterbildung/moocs/project-management-and-future-of-work
In diesem Kurs lernen Sie die wichtigsten Instrumente und Methoden des Projektmanagements kennen. Entwickeln Sie Ihre Fähigkeiten in den Bereichen Teamarbeit, Steuerung, Zeitmanagement, Risikomanagement, Kommunikation und Prozessführung. Dies sind die Grundlagen für die Initiierung, Planung, Durchführung, Dokumentation und Überprüfung von Projekten. Das moderne Leben ist digital. Das Management von Projekten in einem modernen Umfeld erfordert die besondere Berücksichtigung der sich ändernden Arbeitsbedingungen, die mit neuen Technologien und globaler Zusammenarbeit einhergehen. Der Kurs führt Sie in einige der zentralen Themen, Fähigkeiten und Einstellungen ein, die Sie auf die Zukunft der Arbeit für ein modernes Projektmanagement vorbereiten.

**Comment by juliaschmatolla** [comment]
https://github.com/imbitdhbwma/brillianplatform/issues/51#issuecomment-552811866
Nicht mehr relevant für die MA-IMBIT Seite

**Comment by IsabellaMoos** [comment]
> **SW-Lifecycle**
> https://de.coursera.org/learn/software-processes
> Der Software-Lebenszyklus bezieht sich auf alle Phasen eines Softwareprodukts von der Planung, Entwicklung und Nutzung bis hin zur Außerbetriebnahme.
> In diesem Kurs erhalten Sie einen Überblick darüber, wie Software-Teams funktionieren; Welche Prozesse genutzt werden; Was sind branchenüblichen Methoden? Was sind die Vor- und Nachteile?
> 
> The software life cycle refers to all phases of a software product from planning, development and use to obsolescence or decommissioning.
> In this course, you will get an overview of how software teams work? What processes they use? What are some of the industry standard methodologies? What are pros and cons of each?

Unter welchem Thema/auf welcher Seite soll das eingefügt werden?

**Comment by IsabellaMoos** [comment]
> **Schlüsselqualifikationen II - Wissenschaftstheorie und wissenschaftliche Methoden der Wirtschaftsinformatik**
> https://iversity.org/de/courses/wissenschaftliches-denken-arbeiten-und-schreiben-march-2016
> Der Online-Kurs „Wissenschaftliches Denken, Arbeiten und Schreiben“ der Fachhochschule Münster vermittelt alle Grundtechniken wissenschaftlichen Arbeitens von Zitation bis Datenerhebung. Es wird dabei auch über Lerntypen und Arbeitsorganisation gesprochen.
> 
> https://ilias.uni-halle.de/ilias.php?ref_id=61583&cmd=render&cmdClass=ilrepositorygui&cmdNode=ue&baseClass=ilrepositorygui
> Dieser Selbstlernkurs der Universität Halle-Wittenberg erklärt wissenschaftliche Denkweisen und gibt Hilfestellungen in Bezug auf die Anfertigung einer wissenschaftlichen Arbeit. Aktuell stehen die Lernmodule „Wissenschaftliches Denken & Arbeiten“, „Grundlagen des Urheberrechts“, „Planung & Vorbereitung der wissenschaftlichen Arbeit“, „Orientierung, Verwaltung & Dokumentation“ und „Präsentation & Visualisierung“ zur Verfügung. Die Module könne separat und unabhängig voneinander bearbeitet werden und nehmen zwischen 80 und 120 Minuten in Anspruch

Ist erledigt, @NicolasSimon99 kannst du das bitte testen?

**Comment by IsabellaMoos** [comment]
> **Schlüsselqualifikation III - Unternehmenssimulation**
> 
> Planspiel Wein
> http://www.planspielw.de/Welcome.aspx
> In diesem Planspiel übernehmen Sie die Leitung eines Unternehmens, das Trauben einkauft, diese zu Wein verarbeitet und anschließend auf dem Markt anbietet. Wie in einem richtigen Unternehmen übernehmen Sie Kontrolle über die Bereiche Einkauf, Produktion, Vertrieb, Marketing, Personal und Finanzierung. Mit Ihren Entscheidungen müssen Sie sich gegen mehrere Konkurrenten am gleichen Markt durchsetzen und am Ende der Simulation einen möglichst hohen Marktwert Ihres Unternehmens erzielen



> **Schlüsselqualifikation III - Unternehmenssimulation**
> 
> Planspiel Wein
> http://www.planspielw.de/Welcome.aspx
> In diesem Planspiel übernehmen Sie die Leitung eines Unternehmens, das Trauben einkauft, diese zu Wein verarbeitet und anschließend auf dem Markt anbietet. Wie in einem richtigen Unternehmen übernehmen Sie Kontrolle über die Bereiche Einkauf, Produktion, Vertrieb, Marketing, Personal und Finanzierung. Mit Ihren Entscheidungen müssen Sie sich gegen mehrere Konkurrenten am gleichen Markt durchsetzen und am Ende der Simulation einen möglichst hohen Marktwert Ihres Unternehmens erzielen

ist erledigt, @NicolasSimon99 kannst du das bitte testen?

**Comment by IsabellaMoos** [comment]
> **Global Project Management Skills**
> 
> International Project Management
> https://www.edx.org/course/international-project-management-3
> In diesem Kurs werden die Auswirkungen auf das Projektmanagement von Kultur, Sprachvariationen, religiösen, regulatorischen und rechtlichen Praktiken, Technologiepenetration, zeitlicher Orientierung, Geschlechterfragen, Korruption, Ethik, persönlicher Freiheit und politischen Kontexten untersuchrt. Es wird gelernt, wie die Herausforderungen globaler Projekte durch den effizienten Einsatz von Praktiken und Technologien bewältigen werden können. Der Kurs nutzt verfügbare Fallstudien und Beispiele aus Unternehmen, um den Studenten zu helfen, die Fähigkeiten zu verbessern, die sie benötigen, um ein erfolgreiches internationales Projektumfeld zu erkennen und zu fördern.
> 
> International Project Management and Future of Work
> https://www.oncampus.de/weiterbildung/moocs/project-management-and-future-of-work
> In diesem Kurs lernen Sie die wichtigsten Instrumente und Methoden des Projektmanagements kennen. Entwickeln Sie Ihre Fähigkeiten in den Bereichen Teamarbeit, Steuerung, Zeitmanagement, Risikomanagement, Kommunikation und Prozessführung. Dies sind die Grundlagen für die Initiierung, Planung, Durchführung, Dokumentation und Überprüfung von Projekten. Das moderne Leben ist digital. Das Management von Projekten in einem modernen Umfeld erfordert die besondere Berücksichtigung der sich ändernden Arbeitsbedingungen, die mit neuen Technologien und globaler Zusammenarbeit einhergehen. Der Kurs führt Sie in einige der zentralen Themen, Fähigkeiten und Einstellungen ein, die Sie auf die Zukunft der Arbeit für ein modernes Projektmanagement vorbereiten.

Ist erledigt, @NicolasSimon99 kannst du das bitte testen?

**Comment by IsabellaMoos** [comment]
> **SW-Lifecycle**
> https://de.coursera.org/learn/software-processes
> Der Software-Lebenszyklus bezieht sich auf alle Phasen eines Softwareprodukts von der Planung, Entwicklung und Nutzung bis hin zur Außerbetriebnahme.
> In diesem Kurs erhalten Sie einen Überblick darüber, wie Software-Teams funktionieren; Welche Prozesse genutzt werden; Was sind branchenüblichen Methoden? Was sind die Vor- und Nachteile?
> 
> The software life cycle refers to all phases of a software product from planning, development and use to obsolescence or decommissioning.
> In this course, you will get an overview of how software teams work? What processes they use? What are some of the industry standard methodologies? What are pros and cons of each?


> > **SW-Lifecycle**
> > https://de.coursera.org/learn/software-processes
> > Der Software-Lebenszyklus bezieht sich auf alle Phasen eines Softwareprodukts von der Planung, Entwicklung und Nutzung bis hin zur Außerbetriebnahme.
> > In diesem Kurs erhalten Sie einen Überblick darüber, wie Software-Teams funktionieren; Welche Prozesse genutzt werden; Was sind branchenüblichen Methoden? Was sind die Vor- und Nachteile?
> > The software life cycle refers to all phases of a software product from planning, development and use to obsolescence or decommissioning.
> > In this course, you will get an overview of how software teams work? What processes they use? What are some of the industry standard methodologies? What are pros and cons of each?
> 
> Unter welchem Thema/auf welcher Seite soll das eingefügt werden?

Ich habe das jetzt unter "Wirtschaftsinformatik" eingefügt. @NicolasSimon99 kannst du das bitte testen?

**Comment by NicolasSimon99** [comment]
@IsabellaMoos Bei Schlüsselqualifikation II hat sich noch ein Fehler eingeschlichen.
![image](https://user-images.githubusercontent.com/56722197/69036488-4e5bf980-09e6-11ea-8f35-025d32b621d2.png)

**Comment by NicolasSimon99** [comment]
@IsabellaMoos Unter Global Project Management Skills ist der Text leider nicht zu finden.

**Comment by NicolasSimon99** [comment]
@IsabellaMoos Ansonsten erfolgreich getestet.

**Comment by IsabellaMoos** [comment]
> @IsabellaMoos Ansonsten erfolgreich getestet.

@NicolasSimon99 Ich habe deine Anmerkungen überarbeitet.

**Comment by NicolasSimon99** [comment]
Alles erfolgreich getestet.
@JulianeOrt
