### ISSUE TITLE
TESTING - CRM: Spiel testen

### ISSUE THREAD

**Issue by Myprr** [imbitdhbwma/brillianplatform#52]

**Comment by Myprr** [comment]
Bitte einmal durchspielen. Es soll zwischen drinne eine email versendet werden. Das gehört zum Spiel. Wenns nicht klappt, könnt ihr das spiel nicht zuende spielen.

Testzweck: interne mailfunktion.
Als Benutzer könnt ihr student benutzen, falls noch keinen selber angelegt habt.

**Comment by NicolasSimon99** [comment]
@MarvinGi bitte testen.

**Comment by MarvinGi** [comment]
@Myprr @NicolasSimon99  Mail versenden funktioniert nicht, Button ist ausgegraut

**Comment by Myprr** [comment]
> 
> 
> @Myprr @NicolasSimon99 Mail versenden funktioniert nicht, Button ist ausgegraut

Versuche bitte mit Chrome Browser. Da dieser vom Mayr empfohlen wurde.

**Comment by MarvinGi** [comment]
Nochmal neu geladen, jetzt hat alles funktioniert @Myprr

**Comment by JulianeOrt** [comment]
Titeländerung zu: **CRM: interne Mails versenden**

**Comment by JulianeOrt** [comment]
Vermerkt im Backlog (7.11.)
