### ISSUE TITLE
Email Server ändern

### ISSUE THREAD

**Issue by ErikGarstka** [imbitdhbwma/brillianplatform#53]
Übergangslösung für E-Mail Problem: E-Mail Server ändern um von G-mail statt AWS übergangsweise Mails zu versenden

**Comment by JulianeOrt** [comment]
@ErikGarstka läuft dieses Issue auf das Issue #24 raus? Also E-mail Verwaltung bei ICM und CRM?

**Comment by pnt-linii** [comment]
@NicolasSimon99 Bitte an das Testing Team weiter geben. Beim Testcase geht es darum, ob E-Mail vom Server rausgeschickt werden (bei CRM und ICM) z.B. bei Nutzerregistrierung. Es soll auf beiden PServer und QServer funktionieren. 
p/s: Seiten-Forwarding funktioniert im Moment nicht (haha). Wichtig ist aber dass ihr E-Mail vom Server bekommt.
@JulianeOrt

**Comment by NicolasSimon99** [comment]
@StevenHerrenknecht bitte bei Edge und Chrome testen.
@MarcinTrojanski bitte bei Safari und mobil auf Safari testen.

**Comment by NicolasSimon99** [comment]
@MarcinTrojanski und denk ans iPad

**Comment by MarcinTrojanski** [comment]
BrillianCRM: nach der Registrierung landet man bei 404
<img width="1440" alt="Bildschirmfoto 2019-11-15 um 10 27 56" src="https://user-images.githubusercontent.com/56722421/68932310-a13d7300-0792-11ea-93eb-e1aeecb5d6ca.png">

**Comment by StevenHerrenknecht** [comment]
@pnt-linii Bei ICM funktioniert der Erhalt der Conformation Mail. Allerdings der Link zur Bestätigung nicht mehr (Error 404: The origin of the server did not find a current representation of the target source...).
Bei CRM bekomme ich noch nicht mal eine EMail zur Bestätigung (beides getestet auf Chrome).

**Comment by pnt-linii** [comment]
@StevenHerrenknecht @MarcinTrojanski ja wir wissen vom Problem Bescheid und finden gerade ein Lösung dafür.

**Comment by Feederhigh5** [comment]
Müsste jetzt funktionieren, bitte nochmal durchtesten. Insesondere das Versenden des Zertifikats am Ende von brillianICM.
#24

**Comment by pnt-linii** [comment]
Email-Server wurde vom AWS wieder freigeschaltet -> #78 . 
Emails werden vom AWS Emailserver rausgeschickt, anstatt vom Gmail. Bitte dieses Issue schließen @JulianeOrt

**Comment by MarcinTrojanski** [comment]
BrillianCRM: 
so weit hat jetzt alles funktioniert und ich wurde automatisch zum Spiel weitergeleitet.
Probleme gibt es jedoch mit den Videos/GIFs (siehe Bild)
<img width="1440" alt="Bildschirmfoto 2019-11-21 um 13 07 10" src="https://user-images.githubusercontent.com/56722421/69336964-047e4800-0c60-11ea-96f4-f8f8d01c76e2.png">

**Comment by JulianeOrt** [comment]
@DigitaleMedienDHBW wie im Bild oben gezeigt und auch zu Beginn des IT-Projekts von mir schon angesprochen, tritt bei brillianCRM der Fehler mit dem grünen Bild/Video nun auf. Wissen Sie, welches Problem dahinter stecken könnte bzw. wie man das löst?

> BrillianCRM:
> so weit hat jetzt alles funktioniert und ich wurde automatisch zum Spiel weitergeleitet.
> Probleme gibt es jedoch mit den Videos/GIFs (siehe Bild)
> <img alt="Bildschirmfoto 2019-11-21 um 13 07 10" width="1440" src="https://user-images.githubusercontent.com/56722421/69336964-047e4800-0c60-11ea-96f4-f8f8d01c76e2.png">

**Comment by JulianeOrt** [comment]
Der Mail-Server ist noch auf G-mail, daher bleibt dieses Issue noch offen.

**Comment by Feederhigh5** [comment]
E-Mail Versand von G-Mail auf AWS geändert
