### ISSUE TITLE
CRM Registrierbutton reparieren

### ISSUE THREAD

**Issue by ErikGarstka** [imbitdhbwma/brillianplatform#54]
Beim CRM funktioniert das Registrieren über den dafür vorgesehenen Button nicht.

**Comment by JosieRuehling** [comment]
@dfg42 Was ist hier der Status?

**Comment by Feederhigh5** [comment]
Die Übergangslösung funktioniert. E-Mails werden jetzt bis der Amazon Server aktualisiert ist über den SMTP Server von Gmail versendet.
Die confirmation Seite funktioniert allerdings nicht.

<img width="620" alt="BrillianCRMConfirmation" src="https://user-images.githubusercontent.com/48390983/68875166-a7840e80-0702-11ea-8954-fa2f5ebf467f.png">

**Comment by najann** [comment]
Scheinbar funktioniert jetzt alles wieder. 
@NicolasSimon99 testet vorsichtshalber bitte nochmal

**Comment by NicolasSimon99** [comment]
@StevenHerrenknecht bitte testen.

**Comment by StevenHerrenknecht** [comment]
Login funktioniert bei mir immer noch nicht. Die Mail mit dem Aktivierungslink wird gesendet, allerdings ist der Link kein Hyperlink und muss kopiert werden und leitet wieder nicht weiter. 

Erneut Fehler 404 siehe oben.

**Comment by Myprr** [comment]
@StevenHerrenknecht komisch, weil bei mir ist es ein hyperlink.
![grafik](https://user-images.githubusercontent.com/56721991/69044316-02fd1780-09f5-11ea-9b8f-8e1271b2c77c.png)
und wenn ich auf den link clicke funktioniert alles. HAst beim Kopieren Fehler gemacht?
![grafik](https://user-images.githubusercontent.com/56721991/69044359-18724180-09f5-11ea-8eba-91aadf96a6d9.png)
kann mich auch einlaggen mit neuem benutzer.

Hast du auf prod oder test getestet?

**Comment by StevenHerrenknecht** [comment]
@Myprr Im Produktivsystem, wie letztes Mal auch (sollte ich ja auch, oder nicht?).
Wenn nicht löscht mal alle meine Einträge mit meinen Mails s.herrenknecht@t-online, oder steven.herrenknecht@gmail.com.... Vielleicht hat sich was bei der Änderung verhakt. Dann würde ich es nochmal probieren :)

**Comment by Myprr** [comment]
Update:
Fehler im Link beim Klicken auf Register in ICM: http://brillianideas.com:8080/brillianICM/brillianICM/Registration?g=000

**Comment by Myprr** [comment]
update: mussten zurück auf gmail umbauen.
Werden das Testing team informieren wenn AWS Mail Service eingestellt wurde.

**Comment by Myprr** [comment]
Fehler im Link wurde behoben.
E-Mail Versand für die Registrirung funktioniert über Workaround.

@StevenHerrenknecht Der Registrirungsvorgang kann nun auf PROD CRM getestet werden.

**Comment by StevenHerrenknecht** [comment]
@Myprr Registrierung in Prod-CRM erfolgreich getestet! Allerdings wird bei der Bestätigungsmail kein Hyperlink generiert (siehe unten). 
![image](https://user-images.githubusercontent.com/56722211/69740197-4f54ff80-1139-11ea-890d-9b9e17adf3fe.png)

Mit Hyperlink kopieren und einfügen funktioniert es aber.

**Comment by Myprr** [comment]
@StevenHerrenknecht danke.
Issue hiermit abgeschloßen.
Wegen Hyperlink muss das Design Team (@JulianeOrt) entscheiden ob es relevant ist und als ein neues Issue melden.
