### ISSUE TITLE
CRM Kein Bestätigungslink bei Funktion: User manuell hinzufügen

### ISSUE THREAD

**Issue by ErikGarstka** [imbitdhbwma/brillianplatform#55]
Es wird keine Bestätigungsmail verschickt, wenn admins manuell user anlegen

**Comment by dfg42** [comment]
Warten auf #53

**Comment by juliaschmatolla** [comment]
@dfg42 haben sich Neuigkeiten im Issue #53 ergeben?

**Comment by JulianeOrt** [comment]
bitte dran arbeiten und je nach machbarkeit in Sprint 4 verschieben!!

**Comment by Feederhigh5** [comment]
Es soll kein Bestätigungslink versendet werden, wenn Profs User manuell hinzufügen
