### ISSUE TITLE
*DELETED* QUZ: Performance-Probleme sorgen für Wartezeit (besonders WI-Quiz)

### ISSUE THREAD

**Issue by JulianeOrt** [imbitdhbwma/brillianplatform#56]
> * Performance-Probleme sorgen für Wartezeit (besonders WI-Quiz)

Ich denke hier benötigt das Problem ein eigenes Issue

_Originally posted by @pnt-linii in https://github.com/imbitdhbwma/brillianplatform/issues/39#issuecomment-549325821_

**Comment by pnt-linii** [comment]
@ErikGarstka Könntest du hier ein bisschen reinschauen?

**Comment by pnt-linii** [comment]
@JulianeOrt @juliaschmatolla bitte dieses Issue löschen/schließen wegen Irrelevanz bezüglich Firefox-Performanz.

Infos:
https://github.com/imbitdhbwma/brillianplatform/issues/39#issuecomment-552578019

**Comment by JulianeOrt** [comment]
ok, wird gelöscht
