### ISSUE TITLE
CRM: Anpassung von Funktionalität, Responsivität & Browserkompatibilität

### ISSUE THREAD

**Issue by Lilu-S** [imbitdhbwma/brillianplatform#57]
### Browserkompatibilität:
- Videos für Kategorien beginnen in Chrome nicht
- #24 (Safari Mail Problem)
- Bild/Videos sind grün #53 

### Responsivität:
- Bilder responsiv gestalten - sind momentan nur statisch und führen zu weißen Strichen auf der Seite, da sie nur verkleinert werden
- Hintergrundbild verrutscht mit Navigation beim ein/ausblenden der Navigation

### Funktionalität:
-  Funktionen des Filterns in Lecturer Page funktionieren nicht (Lecturer Page mit public/dozent@brilliancrm.com)
- Glossary Link funktioniert nicht
- Fehlende Information über Zurücksetzen des Passworts - es gibt keinen Link für Logout oder zurück und man weiß nicht, ob es geklappt hat (#24 - ist es damit schon gelöst?)
- Navigation funktioniert nicht (Navigation links kann nicht verwendet werden)
- Text-to-Speech ist nicht mit Seitennavigation abgestimmt (Text zu Speech Funktion geht weiter, obwohl man schon zu nächstem Punkt springt)
- Zertifikate wie bei ICM implementieren
- Ladezeit der Videos ist sehr lang - kann diese gekürzt werden?

### Fehlender Content für Verbesserung UX: (BITTE NICHT BEARBEITEN, SONDERN ZUERST FUNKTIONALITÄT SICHERSTELLEN)
- Welche Log-In Daten müssen verwendet werden?
- Bescheibung von brillianCRM fehlt -> Was ist meine Aufgabe in dem Spiel? Introduction zu brillianCRM für Erstnutzer
- Was zeigt mir die Statusleiste an?

@ErikGarstka Fehlender Content könnte das Projekt Management Team übernehmen?

**Comment by JulianeOrt** [comment]
wichtig: **Änderungen im Content** muss **zuerst** mit dem **Product Owner abgeklärt** werden, da nur die Funktionalität der Spiele garantiert werden muss und der Inhalt nur bei Fehlern abgeändert werden darf!

**Comment by JosieRuehling** [comment]
Warten auf E-Mail Funktionalität.

**Comment by JulianeOrt** [comment]
https://github.com/imbitdhbwma/brillianplatform/issues/53#issuecomment-557059653

bitte nun an diesen Fehlern weiterarbeiten, da das Mailproblem nun gelöst wurde. @ErikGarstka 
@NicolasSimon99 je nachdem braucht das Technik Team nochmal weitere Screenshots, soweit ich weiß hat @MarcinTrojanski den Fehler mit den grünen Fotos/Videos in Safari gehabt, tritt das auch in Chrome auf?

**Comment by NicolasSimon99** [comment]
@StevenHerrenknecht bitte testen und Feedback an juliane geben.

**Comment by StevenHerrenknecht** [comment]
@MarvinGi Bitte teste du das, da du das Spiel bereits durchgespielt hast, ich bin ja für ICM im Gegenzug verantwortlich. Danke dir!

**Comment by JulianeOrt** [comment]
Was ist hier der Status? Das gesamte CRM muss durchgespielt werden, damit ein reibungsfreies Spiel garantiert werden kann für Herr Bendl.
@StevenHerrenknecht @MarvinGi @NicolasSimon99 bitte startet damit und macht Screenshots von Fehlern, sobald etwas nicht funktioniert.

**Comment by MarvinGi** [comment]
Gestet auf Chrome und Edge, keine Fehler gefunden @JulianeOrt @NicolasSimon99

**Comment by JulianeOrt** [comment]
CRM wird hiermit abgeschlossen
