### ISSUE TITLE
Passwort Safe erstellen & verwalten

### ISSUE THREAD

**Issue by dfg42** [imbitdhbwma/brillianplatform#59]
Für die Verwaltung aller Passwörter.

**Comment by JosieRuehling** [comment]
@dfg42 Was ist hier der Status?

**Comment by Myprr** [comment]
Update: 
Am Ende soll eine PDF erstellt werden, in der alle PWs gelistet sind.
Dennoch brauchen wir secure password ablage ort (Keepass o.Ä.)

**Comment by juliaschmatolla** [comment]
@dfg42 @ErikGarstka wurde schon in zwei Sprints verschoben, still in progress?

**Comment by JulianeOrt** [comment]
bitte fertig stellen bis morgen oder zu Sprint 4 verschieben!!

**Comment by dfg42** [comment]
@ErikGarstka muss noch geklärt werden, ob Prof. Mayr das i.O. findet?

**Comment by ErikGarstka** [comment]
@dfg42 Nein, das wurde bereits mit ihm abgeklärt. Bitte asap lösen

**Comment by Feederhigh5** [comment]
> Update:
> Am Ende soll eine PDF erstellt werden, in der alle PWs gelistet sind.
> Dennoch brauchen wir secure password ablage ort (Keepass o.Ä.)
Das ist ungefähr was Professor Mayr gesagt hat.

Momentan haben wir eine Lösung für den Betrieb mit Keepass für neue Passwörter in Benutzung. Wir leiten dir diese weiter und du kannst gucken ob Keepass die Anforderungen erreicht (und alte Passwörter ergänzt) oder ob du etwas anderes verwenden möchtest.
So oder so brauchen wir dann eine vollständige Lösung mit allen alten und neuen Passwörtern.
Professor Mayr bekommt am Ende eine PDF im Klartext.

**Comment by dfg42** [comment]
@JosieRuehling @juliaschmatolla @JulianeOrt @ErikGarstka @Feederhigh5 @Myprr 
Ich habe die Keepass Datei von Murad erhalten und einige Passwörter in ein neu erstelltes Dashlane Konto übertragen. Das Problem ist noch die 2FA, die sich nur bedingt abschalten lässt, desshalb wäre die Idee die verschlüsselte Keepass Datei zu verwenden und diese bei Bedarf zu verschicken. Das Passwort soll dann mündlich weitergegeben werden.

**Comment by dfg42** [comment]
KeePass Passwort Safe wurde erstellt und verteilt. Passwörter können am Ende ausgedruckt und an Prof. Mayr übergeben werden.
