### ISSUE TITLE
Security für web xml 

### ISSUE THREAD

**Issue by Lara-u** [imbitdhbwma/brillianplatform#60]
Passwort für Mail-User mit vault abspeichern und in Web XML re­fe­ren­zie­ren.
Das Gilt für ICM und CRM.

**Comment by Myprr** [comment]
Status:
Da Vault Umsetzung doch umständig ist, soll erst mal mit Prof. Mayr besprochen werden ob wir doch ein privates GitHub kriegen. Wenn ja, dann ist kein Bedarf an der Umsetzung von Vault da.

**Comment by Myprr** [comment]
Es wird privates GitHub repo geben.
Task ist canceled.
#61
