### ISSUE TITLE
1. Go-Live

### ISSUE THREAD

**Issue by JosieRuehling** [imbitdhbwma/brillianplatform#62]
Bitte am Mittwoch, den 13.11. die schon vollständig getesteten Issues produktiv setzen.

**Comment by JulianeOrt** [comment]
Die Änderungen sind jetzt live. Da aber noch einige Fehler auftreten, brauchen wir weiteres Testing, damit die Änderungen erfolgreich umgesetzt sind.
@NicolasSimon99 könntet ihr bitte brillianIDEAS durchgehen und von jedem Fehler, der auftritt (Chrome & Safari) einen Screenshot machen, damit @najann an der Korrektur arbeiten kann. Danke! 
**Screenshots direkt hier posten.**

**Comment by NicolasSimon99** [comment]
@MarcinTrojanski 
@StevenHerrenknecht 
@MarvinGi 
lass uns mal alle zusammen grad durchtesten!

**Comment by JosieRuehling** [comment]
![image](https://user-images.githubusercontent.com/56722097/68849877-2d886100-06d3-11ea-80fe-ad602cf36221.png)

Startseite wird falsch angezeigt. BrillianIDEAS Schriftzug ist nicht vorhanden. Krakenarme werden von zu großem Stern überdeckt. Getestet in Chrome.

**Comment by MarcinTrojanski** [comment]
> ![image](https://user-images.githubusercontent.com/56722097/68849877-2d886100-06d3-11ea-80fe-ad602cf36221.png)
> 
> Startseite wird falsch angezeigt. BrillianIDEAS Schriftzug ist nicht vorhanden. Krakenarme werden von zu großem Stern überdeckt. Getestet in Chrome.

gleicher Fehler bei Safari.

**Comment by najann** [comment]
könnt ihr bitte auch jeweils ein Foto von den Fehlermeldungen in der developer console mit einfügen?

**Comment by MarvinGi** [comment]
![Screenshot_20191114-114454](https://user-images.githubusercontent.com/56722300/68850444-552bf900-06d4-11ea-8ee4-8cb90f465f98.png)
Das Wort "Wirtschaftswissenschaften" wird am rechten Rand abgeschnitten.

**Comment by StevenHerrenknecht** [comment]
@najann ![Anzeigefehler Startseite](https://user-images.githubusercontent.com/56722211/68850556-860c2e00-06d4-11ea-806f-b34f22455ce3.PNG)


Habe lediglich diesen Anzeigefehler mit den Starticons gefunden, ansonsten sind alle Fehler behoben an denen ich gearbeitet hatte.

**Comment by MarcinTrojanski** [comment]
**DB Quiz:** Das "Zur Auswertung" Feld ist sehr weit nach unten gewandert, es wird zwar dadurch das Problem mit der Überlappung behoben, ist ja aber nicht so die optimale Lösung. Ich gehe davon aus, dass als Referenzpunkt das letzte Wortfeld auf der linken Seite gewählt wurde. Könnte man nicht das Feld fest unter den Lösungen platzieren, sodass es sich nicht. bei der Lösungseingabe immer wieder verschiebt?

**Comment by najann** [comment]
@MarcinTrojanski 
@NicolasSimon99 
@StevenHerrenknecht 
@MarvinGi 
Kurze Frage: Habt ihr eure caches/history gelöscht vor dem testen? Besonders die safari Fehler können Isabell und ich nicht nachvollziehen

**Comment by StevenHerrenknecht** [comment]
@najann Habe den Cache gelöscht, trotzdem werden die Icons nicht angepasst in Chrome. In Edge tritt das Problem komischerweise nicht auf...

**Comment by MarcinTrojanski** [comment]
> @MarcinTrojanski
> @NicolasSimon99
> @StevenHerrenknecht
> @MarvinGi
> Kurze Frage: Habt ihr eure caches/history gelöscht vor dem testen? Besonders die safari Fehler können Isabell und ich nicht nachvollziehen

Ja hatte meinen Cache gelöscht gehabt. Am. Anfang wurde es normal angezeigt, beim refresh wurde dann das Feld so groß. Habe die Seite jetzt nochmal ein einem neuen Tab geöffnet und es passiert nicht nochmal!

**Comment by MarcinTrojanski** [comment]
Ich weiß gerade nicht wie weit ihr seit bezüglich der zurück Tasten, jedoch wird bei der Rückkehr in das IMBIT CUR nur die Hälfte der Sachen angezeigt
<img width="1440" alt="Bildschirmfoto 2019-11-14 um 17 37 41" src="https://user-images.githubusercontent.com/56722421/68876998-a43e5200-0705-11ea-9270-8953ede31cfd.png">

**Comment by MarcinTrojanski** [comment]
**iPhone Safari Hintergrund CUR & DL:** Wenn man das CUR oder DL öffnet, wird der Hintergrund als Video abgespielt, erst wenn man das wegklickt kann man den Inhalt sehen.
<img width="1440" alt="Bildschirmfoto 2019-11-14 um 17 37 41" src="https://user-images.githubusercontent.com/56722421/68883156-bec9f880-0710-11ea-87a6-3896ae68ec7a.png">

**Comment by najann** [comment]
Also das mit den kleineren Icons in der Rocketbar geht hoffentlich weg wenn @ErikGarstka das ganze mit css gemacht hat. Das mit dem video kann ich jetzt leider nicht ändern, ist aber auch fraglich wie wichtig das jetzt ist....

**Comment by JulianeOrt** [comment]
@najann dann bitte das Video für mobile entfernen, da dies laut PO nicht wichtig ist.

**Comment by najann** [comment]
@MarcinTrojanski ich habe gerade noch mal was beim video geändert. kannst du in 10-15 min bitte nochmal testen ob das auf iOS dann besser klappt mit dem Hintergrund?

**Comment by MarcinTrojanski** [comment]
Das Video läuft auf allen beteiligten Seiten ganz gut! Einziges Problem besteht nur noch mit der Menüleiste, die entweder nicht sichtbar oder nur teilweise sichtbar ist, aber sich dann nicht anklicken lässt.

**Comment by najann** [comment]
@JulianeOrt können wir das issue dann schließen? die Menüleiste ist ja bei einem anderen issue mit drin

**Comment by JulianeOrt** [comment]
Ja, wird somit geschlossen
