### ISSUE TITLE
Inhalte der alten Website unter Curriculum integrieren

### ISSUE THREAD

**Issue by linafodi** [imbitdhbwma/brillianplatform#69]
Wenn man auf "IMBIT Curriculum" klickt soll sich eine Zwischenseite öffnen bei der man aus verschiedenen PDFs auswählen können soll. Die PDFs sollen sich dann in einem neuen Fenster öffnen. Die folgenden Dokumente sollen eingefügt werden: 

"Curriculum" - die jetzige PDF soll erhalten bleiben 
"Erstsemesterinfos" - [IMBIT_Erstsemesterinfos.pdf](https://github.com/imbitdhbwma/brillianplatform/files/3850629/IMBIT_Erstsemesterinfos.pdf)
"Projekte" und "News & Events" - Die Inhalte dazu findet ihr [hier.](https://drive.google.com/drive/folders/12nFdS_5HXYat-frWJyWSl-jwjBQ20ArW). Die Webarchive Files lassen sich nur mit Safari öffnen.

![Bildschirmfoto 2019-11-15 um 09 58 13](https://user-images.githubusercontent.com/56722126/68930736-4fdfb480-078f-11ea-8000-82118d64f03b.png)

**Comment by linafodi** [comment]
relates to #43

**Comment by linafodi** [comment]
*EDIT* nach Retrospective: doch keine neue Seite sondern lieber ein Overlay, Liste oder ähnliches @ErikGarstka

**Comment by linafodi** [comment]
@lukas-marketing schau mal bei den Erstsemesterinfos rein, was man von eurem "Studieninfo"-pdf noch dazu machen könnte

**Comment by linafodi** [comment]
Prof. Mayr hatte geäußert gerne mal einen Blick darauf zu werfen, was für Inhalte der alten Website aufgriffen wurden. Könnt ihr mir eine URL zur jeweiligen Seite (auf dem Test-Server) schicken, auf dem Prof. Mayr das sehen kann? @redisa @najann

**Comment by redisa** [comment]
@linafodi auf dem Testserver sind die Dateien jetzt [hier](http://18.197.147.12/#imbit) einsehbar. Bei einem zu flachen Fenster gibt es beim ausklappen der Links noch Überlagerungen. Ich versuche mich noch darum zu kümmern.

**Comment by jessilenwell** [comment]
Herr Mayr hat grade eine Mail geschickt, das das Dokuement was unter Erstsemert liegt nicht mehr aktuell ist. Hier nochmal seine genauen Worte: 

Hallo zusammen,

bitte löschen Sie die bisherige Datei IMBIT_Erstsemesterinfos und verwenden Sie nur noch die aktuelle beigefügte Version. Es haben sich ja doch einige URLs geändert und auch die eine oder andere Detailinformation.

Mit freundlichen Grüßen 
Prof. Peter Mayr 


----------------

Anbei das Dokument. @redisa könntest du das bitte austauschen? 
[IMBIT_Erstsemesterinfos.pdf](https://github.com/imbitdhbwma/brillianplatform/files/3901208/IMBIT_Erstsemesterinfos.pdf)

**Comment by redisa** [comment]
@jessilenwell Ich habe das Dokument ausgetauscht.

@linafodi kannst du bitte morgen mit Professor Mayr absprechen, ob es so seinen Vorstellungen entspricht?

@NicolasSimon99 Könnt ihr bitte auf den unterschiedlichen Geräten die Darstellung testen?

**Comment by linafodi** [comment]
@redisa die Überlagerungen sind für Prof. Mayr kein Problem, die Liste ist so wie sie ist damit ok!
