### ISSUE TITLE
Backlog Aufgaben definieren 

### ISSUE THREAD

**Issue by linafodi** [imbitdhbwma/brillianplatform#7]
Mit Backlog ist gemeint: die groben Aufgabenstellungen, die in unserem Projekt zu erfüllen sind zu definieren und gerne parallel zu GitHub eine Liste (Word oder Excel) an PMO schicken!

**Comment by JulianeOrt** [comment]
Wir sind dabei, die bisherige Excel-Liste zu evaluieren und werden diese in eine neue, strukturierte Excel-Liste übertragen. Das grobe Gerüst für den Backlog steht. Details werden im Gespräch mit dem PO geklärt.

**Comment by LauraBrinks** [comment]
Alle Aufgaben mit Priorität 1 wurden als Issues in GitHub übertragen.
Je nachdem wie viel Zeit wir noch haben werden wir aus der Excel-Liste (unter Ordner Design -> Liste Priorisiert) Themen mit Priorität 2 als Issues in GitHub einwerfen.

**Comment by JulianeOrt** [comment]
Prio 1 für Product Owner:

Sprint 1:
Launchbar/Menüleiste GitHub#26
Links funktionieren nicht (orange) GitHub#21
Serious Games -> Mail registrierung GitHub#24
“Responsivität” bei CUR lässt Optionen verschwinden -> Nicolas
STR - Wie dual bin ich verschwindet hinter Hintergrund Github#27
CUR - Hintergrund GitHub#20
QUZ - Verschiebung der Inhalte, Ansichtsprobleme, Fragen nicht funktionierend (29 bis 43) @Erik einzelne Aufzählung? GitHub#31
QUZ: Responsivität bei Schrift GitHub#28


Sprint 2:
Inhalt fehlerhaft -> Rechtschreibfehler
Videos grün -> Sobald Mail Registrierung geht
