### ISSUE TITLE
CUR: Implementierung der PDF-Datein 

### ISSUE THREAD

**Issue by juliaschmatolla** [imbitdhbwma/brillianplatform#70]
Related to Issue #43 
Bitte nur IMBIT_Research_Methods_Schuster.pdf, Vorlage_fuer_Posterpraesentation.pptx
Genauere Informationen siehe Kommentare des related Issues

**Comment by IsabellaMoos** [comment]
Ist erledigt, @NicolasSimon99 kannst du das bitte testen?

**Comment by linafodi** [comment]
@NicolasSimon99 wurde das getestet?

**Comment by NicolasSimon99** [comment]
Ja erfolgreich getestet.
@JulianeOrt
