### ISSUE TITLE
CUR: Neue MOOCs Implementieren  

### ISSUE THREAD

**Issue by juliaschmatolla** [imbitdhbwma/brillianplatform#72]
Related Issue #36 hier wurden verschiedene MOOCs rausgesucht und nummeriert, unten genannte MOOCs verbinden

HR: Bitte MOOC 1
Entrepreneurship: Bitte MOOC 4
HR Management: Bitte MOOC 2

**Comment by stinaeinberger** [comment]
Sollen die Beschreibungen auch angepasst werden? Aktuell ist die Beschreibung auf Deutsch, die neuen Beschreibungen aus Issue #36 sind auf Englisch. Zu MOOC 1 gibt es keine neue Beschreibung, dann wäre HR auf Deutsch beschrieben und die anderen beiden auf Englisch.

**Comment by juliaschmatolla** [comment]
Wir implementieren erstmal auf Englisch, da die Kurse auch auf Englisch sind - Beschreibung des Kurses 1 ist wie folgt: 
This course explains what happiness at work looks like, why it matters, and how to cultivate it. It begins by defining happiness and making the case that happiness at work improves the performance of individual employees and organizations as a whole, increasing innovation, productivity, engagement, retention, and the quality of their work.

**Comment by stinaeinberger** [comment]
ist umgesetzt, bitte testen @NicolasSimon99

**Comment by juliaschmatolla** [comment]
@NicolasSimon99 bitte testen und in done verschieben, wenn erfolgreich - Danke!

**Comment by NicolasSimon99** [comment]
@MarvinGi bitte testen.

**Comment by MarvinGi** [comment]
> @MarvinGi bitte testen

gestet & alles funktioniert
