### ISSUE TITLE
Adminoberfläche BrillianICM 

### ISSUE THREAD

**Issue by jessilenwell** [imbitdhbwma/brillianplatform#74]
- Hintergrund auf "freundlich ICM"; Weltkugel, schöne Farben, Anmutung ähnlich wie das Spiel und nicht so wie bei CRM

**Comment by JulianeOrt** [comment]
<img width="806" alt="Screenshot 2019-11-19 at 12 27 59" src="https://user-images.githubusercontent.com/36894965/69142927-2349d680-0ac8-11ea-8040-617a0346edf7.png">

![watercolor map](https://user-images.githubusercontent.com/36894965/69143040-5f7d3700-0ac8-11ea-8f3f-19ecf523881e.jpg)
das ist das bild dazu

opacity auf text hintergrund auf ca. 95%

**Comment by IsabellaMoos** [comment]
> <img alt="Screenshot 2019-11-19 at 12 27 59" width="806" src="https://user-images.githubusercontent.com/36894965/69142927-2349d680-0ac8-11ea-8040-617a0346edf7.png">
> 
> ![watercolor map](https://user-images.githubusercontent.com/36894965/69143040-5f7d3700-0ac8-11ea-8f3f-19ecf523881e.jpg)
> das ist das bild dazu
> 
> opacity auf text hintergrund auf ca. 95%

@NicolasSimon99 bitte testen :)

**Comment by NicolasSimon99** [comment]
@MarcinTrojanski melde dich bitte mal als Admin an und teste sowohl am laptop als auch auf dem iPad.

**Comment by LauraBrinks** [comment]
Der Hintergrund soll wieder geändert werden, da die Farben hier vermuten lassen, dass ein geografischer Sinn (Temperatur, Niederschlag) dahintersteckt. Stattdessen soll etwas aus der ICM Einstiegsseite als Hintergrundbild genommen werden. 
![Web_Background](https://user-images.githubusercontent.com/56722107/69421803-4f609400-0d22-11ea-866d-3f7731ce31f4.png)

**Comment by IsabellaMoos** [comment]
> Der Hintergrund soll wieder geändert werden, da die Farben hier vermuten lassen, dass ein geografischer Sinn (Temperatur, Niederschlag) dahintersteckt. Stattdessen soll etwas aus der ICM Einstiegsseite als Hintergrundbild genommen werden.
> ![Web_Background](https://user-images.githubusercontent.com/56722107/69421803-4f609400-0d22-11ea-866d-3f7731ce31f4.png)

wurde eingefügt, @NicolasSimon99 kannst du das bitte testen?

**Comment by NicolasSimon99** [comment]
@StevenHerrenknecht bitte testen.

**Comment by StevenHerrenknecht** [comment]
Getestet auf Chrome und Edge. Richtiger Hintergrund wurde eingefügt.
@JulianeOrt Ist es absichtlich, dass die erste von den drei Textboxen durchsichtig ist und Box zwei und drei nicht, oder ist das ein Fehler im Design?

![image](https://user-images.githubusercontent.com/56722211/69741833-081c3e00-113c-11ea-94bd-dc400536631b.png)

**Comment by JulianeOrt** [comment]
> Getestet auf Chrome und Edge. Richtiger Hintergrund wurde eingefügt.
> @JulianeOrt Ist es absichtlich, dass die erste von den drei Textboxen durchsichtig ist und Box zwei und drei nicht, oder ist das ein Fehler im Design?
> 
> ![image](https://user-images.githubusercontent.com/56722211/69741833-081c3e00-113c-11ea-94bd-dc400536631b.png)

@IsabellaMoos bitte alle Boxen im einheitlichen Stil mit der gleichen Opacity. Danke!

**Comment by MarcinTrojanski** [comment]
Auf Safari ist der Hintergrund immer noch weiß. Cache wurde vorher gelöscht.
<img width="1440" alt="Bildschirmfoto 2019-11-28 um 13 18 40" src="https://user-images.githubusercontent.com/56722421/69805797-bded9800-11e1-11ea-8b5c-5f0a682cef1b.png">

**Comment by MarcinTrojanski** [comment]
Auf iOS wird der Hintergrund dupliziert, ich denke aber nicht dass das eine so große Priorität hat.
![IMG_4054](https://user-images.githubusercontent.com/56722421/69806995-7b798a80-11e4-11ea-9a7c-e4d7044205ca.PNG)

**Comment by IsabellaMoos** [comment]
> > Getestet auf Chrome und Edge. Richtiger Hintergrund wurde eingefügt.
> > @JulianeOrt Ist es absichtlich, dass die erste von den drei Textboxen durchsichtig ist und Box zwei und drei nicht, oder ist das ein Fehler im Design?
> > ![image](https://user-images.githubusercontent.com/56722211/69741833-081c3e00-113c-11ea-94bd-dc400536631b.png)
> 
> @IsabellaMoos bitte alle Boxen im einheitlichen Stil mit der gleichen Opacity. Danke!

Ich habe es angepasst, @NicolasSimon99 magst du das bitte nochmal testen?

**Comment by MarcinTrojanski** [comment]
@IsabellaMoos @JulianeOrt Funktioniert jetzt alles, alle Boxen sind transparent in Safari!

**Comment by StevenHerrenknecht** [comment]
@IsabellaMoos @JulianeOrt Auch im Chrome Browser wird alles richtig angezeigt.
