### ISSUE TITLE
Re-enable AWS Simple E-Mail Service

### ISSUE THREAD

**Issue by Feederhigh5** [imbitdhbwma/brillianplatform#78]
E-Mail Service von Amazon momentan wegen Spamversand gesperrt.
Fragen beantworten und Amazon um Freigabe bitten:
Once you have addressed the root cause, please tell us:
A) What you determined was the root cause of the vulnerability,
B) What changes you have made in your systems or processes, and
C) An explanation of how those changes will prevent the issue from continuing in the future.

**Comment by Feederhigh5** [comment]
Wir haben AWS geantwortet und warten auf eine Rückmeldung. Um zu klären, ob der Hacker Zugriff auf die AWS Konsole hatte, haben wir folgende Frage an Amazon gestellt. Hier warten wir noch auf eine Rückmeldung.
Could the hacker add his Identitiy just with the SMTP credentials or is the new Email Identity proof that he had management console acces?

--Verbindungen zu anderen Issues:
Determine root cause: #76 
What changes you have made: #77

**Comment by Feederhigh5** [comment]
Noch nicht geclosed, warten auf Rückmeldung von Amazon.

**Comment by Myprr** [comment]
AWS SES ist wieder freigeschaltet.
![grafik](https://user-images.githubusercontent.com/56721991/69009861-ff688280-0959-11ea-8039-4701cb14aafd.png)
