### ISSUE TITLE
QUZ Favicon einstellen

### ISSUE THREAD

**Issue by ErikGarstka** [imbitdhbwma/brillianplatform#79]
Beim Quiz muss noch das Favicon zum Kraken geändert werden:
![grafik](https://user-images.githubusercontent.com/56722214/68947020-b0cdb380-07b4-11ea-86b6-fec698cd7ba7.png)

**Comment by JulianeOrt** [comment]
statt Kraken sollte/könnte man sich laut PO auch ein Symbol passend zu brillianQ überlegen.

**Comment by JulianeOrt** [comment]
Update: 
"bitte kein großer Aufwand: Nehmen sie doch einfach das (verkleinerte) Q-Piktogramm aus der Launchbar; das ist dann auch nutzerfreundlich."
@ErikGarstka dann so :)

**Comment by najann** [comment]
Ist jetzt vorhanden

**Comment by NicolasSimon99** [comment]
Bei Chrome und Edge erfolgreich getest.

**Comment by NicolasSimon99** [comment]
@MarcinTrojanski kannst du das bitte noch bei Safari am Mac / iPad / iPhone angucken.

**Comment by MarcinTrojanski** [comment]
Also beim iPhone und iPad werden meines Wissens nach sowieso keine Icons angezeigt, wodurch ich das auch nicht sehen konnte. Auf dem Laptop in Safari war es sichtbar.

**Comment by JulianeOrt** [comment]
Abgeschlossen.

**Comment by JulianeOrt** [comment]
achtung: es ist zwar geändert, allerdings zum Krakenkopf und nicht zum "Q" Symbol, das man in der Launchbar sieht. Daher wird das Issue wieder geöffnet. Bitte bis zum Sprintende anpassen.
<img width="142" alt="Screenshot 2019-11-28 at 10 04 41" src="https://user-images.githubusercontent.com/36894965/69792225-86bdbd80-11c6-11ea-8ace-eb124f597ebf.png">

**Comment by najann** [comment]
@JulianeOrt Wir hatten uns absichtlich für den krakenkopf entschieden, da auf der Quiz "homepage" schon ein favicon eingestellt war und dies wie überall anders der krakenkopf war.

**Comment by JosieRuehling** [comment]
Bitte morgen mit PO nochmal abklären. @JulianeOrt @najann

**Comment by najann** [comment]
habs jetzt einfach zum Q geändert.

**Comment by MarcinTrojanski** [comment]
Das Q wird auf Safari angezeigt.

**Comment by najann** [comment]
@JulianeOrt  können wir das dann schließen?

**Comment by JulianeOrt** [comment]
funktioniert auf dem Testserver, daher abgeschlossen
