### ISSUE TITLE
CRM: User Löschen

### ISSUE THREAD

**Issue by Myprr** [imbitdhbwma/brillianplatform#80]
Als Public@brilliancrm.com Benutzer ist es nicht möglich andere Benutzer zu löschen.

**Comment by Myprr** [comment]
![delete user CRM](https://user-images.githubusercontent.com/56721991/69055659-998a0280-0a0e-11ea-82be-08daa918efda.PNG)

**Comment by juliaschmatolla** [comment]
@Myprr @ErikGarstka bitte einen Sprint hinzufügen

**Comment by Myprr** [comment]
Ist anscheiend nicht mehr der Fall. Konnte eben Benutzer problemlos löschen.
Eben auf 2 PC in Firefox und Safari getestet.
