### ISSUE TITLE
Nutzerverwaltung: Professoren in Brillian Quiz Datenbanken anlegen

### ISSUE THREAD

**Issue by Lara-u** [imbitdhbwma/brillianplatform#82]
Alle Professoren des Studiengangs IMBIT in der Nutzerverwaltung Datenbank anlegen für Brillian Quiz.

**Comment by Lara-u** [comment]
Ich erstelle zunächst eine Liste mit allen Professoren des IMBIT Studiengangs.

**Comment by Lara-u** [comment]
Hier eine Liste mit zunächst den Professoren, die wir hatten. Herr Mayr wollte eine vollständige Liste bei Frau Kutny anfragen. 

[Professoren- Liste.xlsx](https://github.com/imbitdhbwma/brillianplatform/files/3879045/Professoren-.Liste.xlsx)

**Comment by JulianeOrt** [comment]
sind die Professoren schon angelegt und kann das Issue damit geschlossen werden? @Lara-u

**Comment by Lara-u** [comment]
ja die Professoren sind jetzt angelegt. @JulianeOrt

**Comment by Lara-u** [comment]
Die Dozenten die in der ersten Liste gefehlt haben wurden jetzt ebenfalls angelegt. 

Es kann nun gegebenenfalls getestet werden @NicolasSimon99

**Comment by pnt-linii** [comment]
Die Dozenten sind beiden auf Prod und Test angelegt. Es macht wenig Sinn, an das Testing Team weiterzuleiten. Ich schließt deshalb dieses Issue.
