### ISSUE TITLE
AWS Emailserver Versandregel

### ISSUE THREAD

**Issue by Feederhigh5** [imbitdhbwma/brillianplatform#83]
Versand von E-Mails im AWS Mail Server wenn möglich eingrenzen, sodass nur von unseren Anwendungen aus E-Mails versendet werden können.

**Comment by JulianeOrt** [comment]
Wie ist der Status hier? ist das bis Sprintende zu beenden? @Feederhigh5

**Comment by Myprr** [comment]
Versand von Emails wurde auf die IP Adressen von P und Q Server beschränkt.
Entsprechende Screenshots sind angeferting, werden hier aus Sicherheitsgründen (Solange GitHub Public ist) nicht gepostet und können/müssen bei mir für die Dokumentation angefragt werden.
