### ISSUE TITLE
LRN: PDFs einbauen

### ISSUE THREAD

**Issue by LauraBrinks** [imbitdhbwma/brillianplatform#84]
Im Digital Learning Bereich unter Serious Games bitte die folgenden PDF-Dateien einbauen: 
Folien zum Vortrag von Dr. Frauke Mörike auf der GALA Jahrestagung 2015 in Rom:
[GALA 2015 Rom, brillianCRM.pdf](https://github.com/imbitdhbwma/brillianplatform/files/3880550/GALA.2015.Rom.brillianCRM.pdf)

Artikel zu Serious Games in der Festschrift anläßlich der Emeritierung von Prof. Dr. Beedgen
[Serious Games, Festschrift Beedgen.pdf](https://github.com/imbitdhbwma/brillianplatform/files/3880551/Serious.Games.Festschrift.Beedgen.pdf)

Die Dateien einfach an den ersten Abschnitt anfügen. 
Außerdem bitte die rot markierte Adresse verlinken. 
![image](https://user-images.githubusercontent.com/56722107/69444636-0b38b800-0d51-11ea-8dbe-3e5a60f2e0af.png)

**Comment by IsabellaMoos** [comment]
Ist erledigt, @NicolasSimon99 kannst du das bitte testen?

**Comment by NicolasSimon99** [comment]
Pdf's erfolgreich verlinkt.
@JulianeOrt
