### ISSUE TITLE
Ergänzung wissenschaftliches Arbeiten: formale Anforderungen

### ISSUE THREAD

**Issue by juliaschmatolla** [imbitdhbwma/brillianplatform#85]
Formal Anforderungen sollen auch zum wissenschaftlichen arbeiten hinzugefügt werden 
@redisa werde nochmal auf dich zukommen

**Comment by juliaschmatolla** [comment]
- Die Kurzzusammenfassung (Abstract) wird in der Sprache der Arbeit bzw. die der Bachelorarbeit in Deutsch und Englisch geschrieben; sie wird in die Arbeit eingebunden 
- Zitierweise: Es gilt die Harvard-Zitation mit Kurzreferenz im Text

**Comment by redisa** [comment]
Die oben genannten Anforderungen wurden probeweise unter "wissenschaftliches Arbeiten" eingefügt. Sollen dazu noch weitere Punkte eingefügt werden oder z.B. die Überschrift angepasst werden? @juliaschmatolla

**Comment by juliaschmatolla** [comment]
Update nach Sprint Ende 3: Der Reiter Tipps wiss. Arbeiten wurde hinzugefügt und muss nun noch mit der richtigen PDF Datei hinterlegt werden.

Durch das Erstellen, der des Drop-Down Menü wurde vorerst vermutet, dass sich das gesamte Menü um den Krakenarm verzogen hat siehe Screenshot Nummer 1:

**Comment by juliaschmatolla** [comment]
<img width="1439" alt="Screen Shot 2019-11-29 at 12 55 52 PM" src="https://user-images.githubusercontent.com/56721935/69871522-5142ce00-12b3-11ea-8269-7ef11abda39d.png">

**Comment by juliaschmatolla** [comment]
Vorerst wurde dies als Fehler vermutet, jedoch wurde die Seite neu geladen und die Darstellung war wieder wie gewohnt. Dies wurde dann auch auf auf einem ios Gerät, in safari, Firefox, Chrome sowie auch auf einem Windows Gerät wieder erfolgreich getestet.

**Comment by juliaschmatolla** [comment]
![WhatsApp Image 2019-11-29 at 1 26 51 PM](https://user-images.githubusercontent.com/56721935/69871729-d62de780-12b3-11ea-8168-4ef5efb615c4.jpeg)
![WhatsApp Image 2019-11-29 at 2 22 44 PM](https://user-images.githubusercontent.com/56721935/69871741-de862280-12b3-11ea-9edf-1b6a7fd1bd91.jpeg)
<img width="1439" alt="Screen Shot 2019-11-29 at 2 16 42 PM" src="https://user-images.githubusercontent.com/56721935/69871753-e2b24000-12b3-11ea-9fe1-61cf8618e1c9.png">

**Comment by JulianeOrt** [comment]
@juliaschmatolla ist das Issue fertig bearbeitet?

**Comment by JulianeOrt** [comment]
wurde ergänzt und wird daher abgeschlossen
