### ISSUE TITLE
CUR: Weltkarte - Links Summer School updaten

### ISSUE THREAD

**Issue by linafodi** [imbitdhbwma/brillianplatform#86]
Einige der Links für die jeweiligen Summer Schools sind bei der Weltkarte (Auslandspraxiserfahrungen) nicht mehr aktuell. 

Bitte updaten: 
University of Almeria: https://www.ual.es
UWE Bristol: https://www.uwe.ac.uk

**Comment by najann** [comment]
Ist gemacht :)

**Comment by NicolasSimon99** [comment]
Links funktionieren.

**Comment by JulianeOrt** [comment]
Abgeschlossen.
