### ISSUE TITLE
ICM: Drag and Drop

### ISSUE THREAD

**Issue by JulianeOrt** [imbitdhbwma/brillianplatform#87]
Noch ein Fehler, der mir beim durchspielen von ICM aufgefallen ist:
![image](https://user-images.githubusercontent.com/56722211/69744149-ecb33200-113f-11ea-839c-9b86d6d30a4d.png)

Man muss die Vereine an die richtige Position ziehen, allerdings werden diese nicht im Drag und Drop dargestellt... @JulianeOrt würdest du bitte ienen neuen Issue erstellen, oder wie wird das geregelt?

_Originally posted by @StevenHerrenknecht in https://github.com/imbitdhbwma/brillianplatform/issues/44#issuecomment-559173107_

**Comment by JulianeOrt** [comment]
zuerst Absprache mit PO am Freitag über Änderung

**Comment by najann** [comment]
@JulianeOrt  was wurde da jetzt abgesprochen ? :)

**Comment by JulianeOrt** [comment]
an den Serious Games sollen wir nach dem PO nichts mehr verändern, daher schließe ich das Issue.
