### ISSUE TITLE
Neue URL für IMBIT Mannheim 

### ISSUE THREAD

**Issue by JosieRuehling** [imbitdhbwma/brillianplatform#89]
Hallo,

durch den Web-Relaunch haben sich die URLs der Studiengänge geändert. IMBIT ist jetzt unter *** www.mannheim.dhbw.de/wi-imbit *** zu erreichen. Bitte ändern sie das im Impressum und an allen anderen Stellen, wo wir auf eventuell auf IMBIT verweisen. Am besten suchen sie nach dem bisherigen www.imbit.dhbw-mannheim.de oder imbit.dhbw-mannheim.de.

Prüfen Sie bitte auch, ob wir irgendwo www.dhbw-mannheim.de verwenden. Das muss jetzt 
*** www.mannheim.dhbw.de *** heißen.

Mit freundlichen Grüßen 
Prof. Peter Mayr

**Comment by NicolasSimon99** [comment]
@StevenHerrenknecht guck mal bitte ob du was findest.

**Comment by StevenHerrenknecht** [comment]
@NicolasSimon99 @JosieRuehling Im Impressum wird noch www.IMBIT.dhbw-mannheim.de verwendet, muss geändert werden in www.mannheim.dhbw.de/wi-imbit  --> (s.o.)

Ansonsten habe ich keine anderen Hyperlinks gefunden, die mich auf eine DHBW Seite verweisen würden, die Herr Mayr oben genannt hat...

**Comment by redisa** [comment]
@StevenHerrenknecht ich weiß, dass zum Beispiel vom wie dual bin ich Quiz aus auf die Seite der DHBW verlinkt wird. Dort wird unter anderem auf https://www.dhbw-mannheim.de/ und https://www.mannheim.dhbw.de/dual-studieren/duales-studium/vorteile-eines-dualen-studiums verlinkt. Beide links funktionieren. Müssen trotzdem alle die mit dhbw-mannheim anfangen geändert werden? Ansonsten wird z.B. von den Praxisphasen aus auch auf die DHBW Seite verlinkt.  Falls die Links verändert werden müssen, bitte nocheinmal alle Stellen herausfinden an denen das der Fall wäre.

**Comment by StevenHerrenknecht** [comment]
@redisa Würde schon sagen das die Links geändert werden sollen in die, die Herr Mayr oben genannt hat. Nicht das die abgeschalten werden und in ein paar Wochen geht nix mehr... Siehe Josies Kommentar

**Comment by JulianeOrt** [comment]
Alle Links müssen wie in der Beschreibung definitiv abgeändert werden.
@StevenHerrenknecht bitte teste wo überall es abgeändert werden muss. Danke!

**Comment by dfg42** [comment]
@JosieRuehling @NicolasSimon99 @StevenHerrenknecht @redisa @JulianeOrt 
Es gibt vermutlich insgesamt 21 Stellen, an denen der alte Link verwendet wird:

![grafik](https://user-images.githubusercontent.com/28921157/69863630-9a882300-129d-11ea-9cc1-28b26fef7fe4.png)

Da es sich nur um einen Link handelt, sollte das relativ problemlos sein. Ich werde das alles ändern.

**Comment by dfg42** [comment]
Alle Links ersetzt.
