### ISSUE TITLE
LRN: Menupunkt Digital Learning testen

### ISSUE THREAD

**Issue by JulianeOrt** [imbitdhbwma/brillianplatform#9]
Menupunkt 2 (Digital Learning) wurde in der Excel-Liste ausgelassen. Bitte auf Probleme und Browserkompabiltät testen: Chrome, Safari, Firefox und Mobile Safari und in die Webseite-Analyse Excel-Liste hinzufügen.

**Comment by NicolasSimon99** [comment]
@StevenHerrenknecht macht bitte den Teil oben links in allen Browsern.
@MartinTrojanski macht bitte den Teil oben rechts in allen Browsern.
@MarvinGi macht bitte den Teil unten rechts in allen Browsern.
@NicolasSimon99 macht den Teil unten links in allen Browsern.

Bitte, gefundene Fehler in das Googlesheet eintragen!

**Comment by MarcinTrojanski** [comment]
Oben rechts wurde getestet... Siehe Google Drive Excel

**Comment by NicolasSimon99** [comment]
Unten rechts und links wurden ebenfalls getestet...Siehe Google Drive
