### ISSUE TITLE
Verlinkung zu Hochspulsport und Weiterbildungsmöglichkeiten 

### ISSUE THREAD

**Issue by jessilenwell** [imbitdhbwma/brillianplatform#90]
Wir hatten beim Teamevent gebrainstormt und die Punkte die Mayr gerne aufnhemen würde, ist das das Sport Angbot und genrelle Weiterbildungsmöglichkeiten auf der WebSeite verlinkt werden. Ich hatte eigentlich gedachte, dass das unter dem IMBIT-Curriculum plaziert werden kann aber da ist es mittlerweile voll auf dem Testserver. Ist es möglich dort noch 2 Sachen einzufügen und die Schrifft kleiner zu machen oder wird das zu voll?
@JulianeOrt wo meinst du kann das noch plaziert werden? Mayr hat das im Meeting vor 2 Wochen an das Design team addressiert. Bzw. @redisa  eventuell hat das Technik Team da eine Idee? 

Links: 
- https://www.mannheim.dhbw.de/dual-studieren/rund-ums-studium/hochschulsport
- https://www.mannheim.dhbw.de/dual-studieren/rund-ums-studium/zusatzqualifikationen?version=3%23Fachthemen

**Comment by jessilenwell** [comment]
Kommentar vom Produkt Owner: 

Hallo zusammen,

an interessanten Angeboten für DHBW-Studierende sollten das Studium Generale - www.studiumgenerale.uni-mannheim.de/de/startseite_dhbw/ - und der Hochschulsport - www.uni-mannheim.de/sport/faq/ - aufgenommen werden. 
* Die derzeit platzierten News&Events- sowie Projekte-Seiten aus dem alten IMBIT-Webauftritt gehören da nicht hin. Es wären dann nur insgesamt vier Einträge.
* Ja, die Schrift dieser vier Punkte (Studienplan, Erstsemesterinfos, Studium Generale, Hochschulsport) kann kleiner werden.
* Die Links hinter den vier Einträgen sollen in neuem Tab geöffnet werden.

Mit freundlichen Grüßen 
Prof. Peter Mayr

**Comment by redisa** [comment]
Habe ich gemacht.
@NicolasSimon99 bitte testen

**Comment by NicolasSimon99** [comment]
Verlinkungen funktionieren.
@JulianeOrt
