### ISSUE TITLE
QUZ: Rechtschreibfehler im Marketing

### ISSUE THREAD

**Issue by JulianeOrt** [imbitdhbwma/brillianplatform#95]
Tippfehler im Mktg.-Quiz

Hallo zusammen,

in der ersten Frage des Mktg.-Quizzes steht als Antwortmöglichkeit "Kundendient" statt Kundendienst". Korrigieren Sie das bitte in der JSON-DDatei udn im HTML-Kode.

Danke
Prof. Peter Mayr

**Comment by IsabellaMoos** [comment]
> Tippfehler im Mktg.-Quiz
> 
> Hallo zusammen,
> 
> in der ersten Frage des Mktg.-Quizzes steht als Antwortmöglichkeit "Kundendient" statt Kundendienst". Korrigieren Sie das bitte in der JSON-DDatei udn im HTML-Kode.
> 
> Danke
> Prof. Peter Mayr

Ist erledigt, @NicolasSimon99 kannst du dir das kurz angucken?
